const state = { user: null, games: [], friends: [], requests: [], notifications: [], lobbies: [], view: 'home', match: null, authMode: 'login', events: null, createLobbyOpen: false, createLobbyGameId: '', selectedLobbyId: '', battleLobbyMode: 'classic', battleLobbyEditMode: '', battleLobbyEditId: '', navalSelectedShipId: '', navalSelectedMode: 'normal', navalOrientation: 'H', navalMirror: false };
const app = document.querySelector('#app');
const toastRegion = document.querySelector('#toast-region');

async function api(path, options = {}) {
  const response = await fetch(path, { headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || 'Operazione non riuscita.');
  return data;
}
function escapeHtml(value) { return String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char])); }
function toast(message) { const node = document.createElement('div'); node.className = 'toast'; node.textContent = message; toastRegion.appendChild(node); setTimeout(() => node.remove(), 3500); }
function initials(name) { return String(name || '?').slice(0, 1).toUpperCase(); }
function formatDate(date) { return new Intl.DateTimeFormat('it-IT', { day: 'numeric', month: 'short' }).format(new Date(date)); }
function matchPlayerName(playerId) { const profile = state.match?.playerProfiles?.find(player => player.id === playerId); return profile?.displayName || profile?.username || playerId; }

async function loadData() {
  const me = await api('/api/me'); state.user = me.user;
  const games = await api('/api/games'); state.games = games.games;
  if (state.user) {
    const [friends, notifications, lobbies] = await Promise.all([api('/api/friends'), api('/api/notifications'), api('/api/lobbies')]);
    Object.assign(state, friends, notifications, lobbies);
    const savedMatchId = sessionStorage.getItem('browser-games-active-match');
    if (!state.match && savedMatchId) {
      try { const savedMatch = await api(`/api/matches/${savedMatchId}`); state.match = savedMatch.match; } catch { sessionStorage.removeItem('browser-games-active-match'); }
    }
    connectEvents();
  }
  render();
}
function connectEvents() {
  if (state.events) state.events.close();
  state.events = new EventSource('/api/events');
  state.events.onmessage = message => {
    try {
      const data = JSON.parse(message.data);
      if (data.type === 'notification.created') { state.notifications.unshift(data.payload); toast(data.payload.type === 'lobby_invite' ? `Hai ricevuto un invito a una lobby da ${data.payload.payload?.from?.displayName || data.payload.payload?.from?.username || 'un amico'}.` : 'Hai una nuova notifica'); render(); }
      if (data.type === 'lobby.updated') {
        const lobby = data.payload; const index = state.lobbies.findIndex(item => item.id === lobby.id);
        if (lobby.status !== 'WAITING') { if (index >= 0) state.lobbies.splice(index, 1); }
        else if (index >= 0) state.lobbies[index] = lobby;
        else if (lobby.privacy === 'public' || lobby.hostId === state.user.id || lobby.playerIds.includes(state.user.id) || lobby.invitedUserIds?.includes(state.user.id)) state.lobbies.unshift(lobby);
        render();
      }
      if (data.type === 'match.started' && data.payload.players?.includes(state.user.id)) { state.match = data.payload; sessionStorage.setItem('browser-games-active-match', data.payload.id); state.view = 'match'; render(); }
      if (data.type === 'game.state_updated' && state.match?.id === data.payload.matchId) { state.match.state = data.payload.state; state.match.sequence = data.payload.sequence; render(); }
    } catch { /* evento non riconosciuto */ }
  };
}

function render() { app.innerHTML = state.user ? `${renderShell()}${renderCreateLobbyModal()}` : renderAuth(); bindEvents(); }
function renderAuth() {
  const register = state.authMode === 'register';
  return `<main class="auth-screen"><section class="auth-card"><div class="brand"><span class="brand-mark">✦</span> Haxed Hub</div><p class="eyebrow">browser games multiplayer</p><h1>${register ? 'Crea il tuo account' : 'Bentornato in arena'}</h1><p class="muted">Una casa condivisa per le tue prossime partite.</p><div class="auth-tabs"><button data-auth="login" class="${!register ? 'active' : ''}">Accedi</button><button data-auth="register" class="${register ? 'active' : ''}">Registrati</button></div><form id="auth-form" class="form"><label>${register ? 'Username' : 'Username o email'}<input name="identity" autocomplete="username" required minlength="3"></label>${register ? '<label>Email<input name="email" type="email" autocomplete="email" required></label><label>Nome visualizzato<input name="displayName" maxlength="40"></label>' : ''}<label>Password<input name="password" type="password" autocomplete="current-password" required minlength="8"></label><div id="form-error" class="error"></div><button class="btn primary" type="submit">${register ? 'Crea account' : 'Entra nell’hub'}</button></form></section></main>`;
}
function renderSidebarFriends() {
  if (!state.friends.length) return '<div class="sidebar-friends"><div class="sidebar-label">Amici</div><div class="sidebar-empty">Nessun amico ancora</div></div>';
  return `<div class="sidebar-friends"><div class="sidebar-label">Amici</div>${state.friends.slice(0, 8).map(friend => `<div class="sidebar-friend"><div class="avatar">${initials(friend.displayName || friend.username)}</div><div><strong>${escapeHtml(friend.displayName || friend.username)}</strong><div class="muted">${friend.status === 'online' ? 'online' : 'offline'}</div></div></div>`).join('')}</div>`;
}
function navigate(view) {
  if (state.view === 'match' && view !== 'match' && state.match?.status === 'IN_GAME') { toast('Partita in corso: usa “Abbandona partita” per uscire.'); return; }
  state.view = view; render();
}
function renderShell() {
  const views = { home: renderHome, games: renderGames, social: renderSocial, lobbies: renderLobbies, match: renderMatch, profile: renderProfile };
  const view = views[state.view] || renderHome;
  const matchLink = state.match?.status === 'IN_GAME' ? '<button data-view="match" class="active">🎮 Partita in corso</button>' : '';
  return `<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">✦</span> Haxed Hub</div><nav class="nav">${[['home','⌂ Home'],['games','◈ Games Hub'],['lobbies','◉ Lobby']].map(([key,label]) => `<button data-view="${key}" class="${state.view === key ? 'active' : ''}">${label}</button>`).join('')}${matchLink}</nav>${renderSidebarFriends()}<div class="sidebar-bottom"><button data-view="profile" class="btn ghost small ${state.view === 'profile' ? 'active' : ''}">◎ Profilo</button><button class="btn ghost small" data-logout>Esci</button></div></aside><main class="main"><header class="topbar"><div><p class="eyebrow">${state.view === 'home' ? 'panoramica' : state.view}</p><h2 style="margin:0">Ciao, ${escapeHtml(state.user.displayName || state.user.username)}</h2></div><div class="identity"><div class="avatar">${initials(state.user.displayName || state.user.username)}</div><span class="pill success">online</span></div></header>${view()}</main></div>`;
}
function renderHome() {
  return `<section class="hero"><div class="hero-content"><p class="eyebrow">la tua prossima partita è qui</p><h1>Gioca insieme.<br>Resta connesso.</h1><p>Scopri giochi multiplayer modulari, crea una lobby e invita le persone con cui vuoi condividere la vittoria.</p><button class="btn primary" data-view="games">Esplora Games Hub →</button></div></section><section class="section"><div class="section-header"><div><p class="eyebrow">selezione</p><h2>Giochi disponibili</h2></div><button class="btn ghost small" data-view="games">Vedi tutti</button></div><div class="grid">${state.games.map(gameCard).join('')}</div></section><section class="section grid"><div class="panel"><p class="eyebrow">social</p><h2>${state.friends.length} amici</h2><p class="muted">${state.notifications.filter(n => !n.readAt).length} notifiche non lette.</p><button class="btn ghost small" data-view="social">Apri amici</button></div><div class="panel"><p class="eyebrow">partite</p><h2>Trova una lobby</h2><p class="muted">Entra in una partita pubblica già pronta.</p><button class="btn ghost small" data-view="lobbies">Vedi lobby</button></div></section>`;
}
function gameCard(game) {
  return `<article class="card game-card"><div class="game-art"><img src="/game-assets/${game.id}/${game.media?.icon || ''}" alt=""></div><div class="game-body"><div class="row"><h3>${escapeHtml(game.name)}</h3><span class="pill success">online</span></div><p class="muted">${escapeHtml(game.description)}</p><div class="game-meta"><span>${game.players.min}–${game.players.max} giocatori</span><span>v${game.version}</span></div><button class="btn primary" data-open-lobby="${game.id}">Crea lobby</button></div></article>`;
}
function renderGames() { return `<section><div class="section-header"><div><p class="eyebrow">catalogo</p><h1>Games Hub</h1><p class="muted">Ogni gioco è un modulo indipendente del catalogo.</p></div></div><div class="grid">${state.games.map(gameCard).join('')}</div></section>`; }
function renderSocial() {
  return `<section><div class="section-header"><div><p class="eyebrow">social graph</p><h1>Amici</h1><p class="muted">Gioca con le persone che conosci.</p></div></div><div class="grid"><div class="panel"><h2>Aggiungi un giocatore</h2><form id="friend-form" class="form"><label>Username<input name="username" placeholder="es. luca_87" required></label><button class="btn primary">Invia richiesta</button></form></div><div class="panel"><h2>Richieste</h2><div class="list">${state.requests.length ? state.requests.map(request => `<div class="list-item"><div><strong>${escapeHtml(request.sender.username)}</strong><div class="muted">richiesta in arrivo</div></div><button class="btn small" data-accept="${request.id}">Accetta</button></div>`).join('') : '<div class="empty">Nessuna richiesta in attesa.</div>'}</div></div></div><div class="section panel"><h2>La tua lista</h2><div class="list">${state.friends.length ? state.friends.map(friend => `<div class="list-item"><div class="identity"><div class="avatar">${initials(friend.displayName || friend.username)}</div><div><strong>${escapeHtml(friend.displayName || friend.username)}</strong><div class="muted">@${escapeHtml(friend.username)}</div></div></div><span class="pill ${friend.status === 'online' ? 'success' : ''}">${friend.status}</span></div>`).join('') : '<div class="empty">Non hai ancora amici. Invita qualcuno a giocare.</div>'}</div></div></section>`;
}
function renderLobbies() {
  const selected = state.lobbies.find(lobby => lobby.id === state.selectedLobbyId) || state.lobbies[0];
  if (selected) state.selectedLobbyId = selected.id;
  const list = state.lobbies.length ? state.lobbies.map(lobby => {
    const game = state.games.find(item => item.id === lobby.gameId); const isHost = lobby.hostId === state.user.id; const isMember = lobby.players.some(player => player.id === state.user.id); const ready = lobby.players.length >= (game?.players.min || 2);
    const action = isHost ? `<button class="btn primary small" data-start-lobby="${lobby.id}" ${ready ? '' : 'disabled'}>${ready ? 'Avvia partita' : `Servono ${game?.players.min || 2} giocatori`}</button>` : isMember ? '<span class="pill">In attesa dell’host</span>' : `<button class="btn small" data-join-lobby="${lobby.id}">Entra</button>`;
    return `<div class="lobby-list-card ${selected?.id === lobby.id ? 'selected' : ''}" data-select-lobby="${lobby.id}"><div class="row"><div><strong>${escapeHtml(game?.name || lobby.gameId)}</strong><div class="muted">${lobby.players.length}/${lobby.maxPlayers} giocatori · host ${escapeHtml(lobby.players.find(p => p.id === lobby.hostId)?.username || 'giocatore')}</div></div>${action}</div></div>`;
  }).join('') : '<div class="empty">Non ci sono lobby pubbliche. Creane una tu.</div>';
  return `<section><div class="section-header"><div><p class="eyebrow">matchmaking leggero</p><h1>Lobby</h1><p class="muted">Scegli il gioco, configura i posti e avvia quando siete pronti.</p></div><button class="btn primary" data-open-lobby="">+ Crea lobby</button></div><div class="lobby-layout"><div class="list">${list}</div>${selected ? renderLobbyPanel(selected) : '<div class="panel empty">Seleziona o crea una lobby.</div>'}</div></section>`;
}
function renderBattleLobbySettings(mode, settings = {}) {
  if (mode === 'classic') return `<label>Set di navi<select name="fleetSet">${Object.values(settings.fleetSets || {}).length ? Object.values(settings.fleetSets).map(set => `<option value="${set.id}" ${set.id === (settings.fleetSet || 'daituunnome') ? 'selected' : ''}>${escapeHtml(set.name)} · ${escapeHtml(set.description)}</option>`).join('') : '<option value="daituunnome">Daituunnome · flotta standard</option><option value="daituunnome2">Daituunnome 2 · flotta numerosa</option><option value="daiunnometu3">Daiunnometu 3 · flotta geometrica</option>'}</select><span class="muted">Tabellone fisso 10×10.</span></label>`;
  const boardOptions = [{ size: 11, budget: 25 }, { size: 13, budget: 30 }, { size: 15, budget: 35 }, { size: 25, budget: 45 }, { size: 35, budget: 55 }, { size: 50, budget: 80 }]; const selectedSize = boardOptions.some(option => option.size === Number(settings.boardSize)) ? Number(settings.boardSize) : 11;
  return `<label>Tabellone Plus<select name="boardSize">${boardOptions.map(option => `<option value="${option.size}" ${selectedSize === option.size ? 'selected' : ''}>${option.size}×${option.size} · ${option.budget} punti deck</option>`).join('')}</select><span class="muted">Formato standard con budget proporzionato.</span></label><label class="check-row"><input type="checkbox" name="abilitiesEnabled" ${settings.abilitiesEnabled !== false ? 'checked' : ''}> Attivare le abilità delle navi</label><label class="check-row"><input type="checkbox" name="specialShotsEnabled" ${settings.specialShotsEnabled !== false ? 'checked' : ''}> Attivare i colpi speciali</label>`;
}
function renderGameLobbySettings(gameId, settings = {}) {
  if (gameId === 'uno') return `<label>Modalità Uno<select name="unoMode"><option value="classic" ${settings.mode === 'classic' || !settings.mode ? 'selected' : ''}>Classica</option><option value="stack" ${settings.mode === 'stack' ? 'selected' : ''}>Stack selvaggio · +2 e +4 accumulabili</option><option value="chaos" ${settings.mode === 'chaos' ? 'selected' : ''}>Caos · regole più infami</option></select></label>`;
  if (gameId === 'wordle-coop') return `<label>Parole contemporanee<input name="wordCount" type="number" min="1" max="5" value="${settings.wordCount || 1}"><span class="muted">La stessa parola tentata aggiorna tutti i tabelloni.</span></label>`;
  if (gameId === 'wordle-competitivo') return `<label>Parole da indovinare<input name="wordCount" type="number" min="1" max="5" value="${settings.wordCount || 1}"></label><label>Modalità<select name="matchMode"><option value="first" ${settings.matchMode !== 'time' ? 'selected' : ''}>Chi indovina prima</option><option value="time" ${settings.matchMode === 'time' ? 'selected' : ''}>Più parole nel tempo</option></select></label><label>Durata in secondi<input name="durationSeconds" type="number" min="30" max="600" value="${settings.durationSeconds || 120}"></label>`;
  return '';
}
function renderLobbyPanel(lobby) {
  const game = state.games.find(item => item.id === lobby.gameId); const isHost = lobby.hostId === state.user.id; const ready = lobby.players.length >= (game?.players.min || 2); const settings = lobby.settings || {};
  const battleMode = state.battleLobbyEditId === lobby.id ? state.battleLobbyEditMode : settings.mode === 'plus' ? 'plus' : 'classic';
  const extra = lobby.gameId === 'battaglia-navale' ? `<label>Modalità<select name="mode" id="lobby-battle-mode"><option value="classic" ${battleMode !== 'plus' ? 'selected' : ''}>Classica · set personalizzabile</option><option value="plus" ${battleMode === 'plus' ? 'selected' : ''}>Plus · deck e poteri</option></select></label>${renderBattleLobbySettings(battleMode, settings)}` : renderGameLobbySettings(lobby.gameId, settings);
  const playerField = game?.players.min === game?.players.max ? `<label>Giocatori richiesti<input value="${game.players.max}" disabled><input type="hidden" name="maxPlayers" value="${game.players.max}"></label>` : `<label>Numero massimo<input name="maxPlayers" type="number" min="${game?.players.min || 2}" max="${game?.players.max || lobby.maxPlayers}" value="${lobby.maxPlayers}"></label>`;
  const invited = lobby.invitedUserIds || []; const inviteableFriends = state.friends.filter(friend => !lobby.players.some(player => player.id === friend.id)); const invitePanel = isHost && lobby.status === 'WAITING' && lobby.privacy === 'private' ? `<div class="section"><p class="eyebrow">invita amici</p>${inviteableFriends.length ? inviteableFriends.map(friend => `<div class="lobby-player"><div class="avatar">${initials(friend.displayName || friend.username)}</div><div><strong>${escapeHtml(friend.displayName || friend.username)}</strong><div class="muted">${invited.includes(friend.id) ? 'Invito già inviato' : 'Amico'}</div></div><button class="btn small" data-invite-friend data-lobby-id="${lobby.id}" data-user-id="${friend.id}" ${invited.includes(friend.id) ? 'disabled' : ''}>${invited.includes(friend.id) ? 'Invitato' : 'Invita'}</button></div>`).join('') : '<p class="muted">Aggiungi prima degli amici per poterli invitare.</p>'}</div>` : '';
  return `<aside class="panel lobby-panel"><p class="eyebrow">lobby selezionata</p><h2>${escapeHtml(game?.name || lobby.gameId)}</h2><p class="muted">${lobby.status === 'WAITING' ? 'In attesa di giocatori' : lobby.status}</p><div class="list"><div class="list-item"><span class="muted">Prossimo gioco</span><strong>${escapeHtml(game?.name || lobby.gameId)}</strong></div><div class="list-item"><span class="muted">Posti</span><strong>${lobby.players.length}/${lobby.maxPlayers}</strong></div><div class="list-item"><span class="muted">Host</span><strong>${escapeHtml(lobby.players.find(p => p.id === lobby.hostId)?.username || 'giocatore')}</strong></div></div><div class="section"><p class="eyebrow">giocatori</p>${lobby.players.map(player => `<div class="lobby-player"><div class="avatar">${initials(player.displayName || player.username)}</div><div><strong>${escapeHtml(player.displayName || player.username)}</strong><div class="muted">${player.id === lobby.hostId ? 'Host' : 'Giocatore'}</div></div></div>`).join('')}</div>${invitePanel}${isHost && lobby.status === 'WAITING' ? `<form id="lobby-settings-form" class="form section"><p class="eyebrow">impostazioni host</p><label>Prossimo gioco<select name="gameId">${state.games.map(item => `<option value="${item.id}" ${item.id === lobby.gameId ? 'selected' : ''}>${escapeHtml(item.name)}</option>`).join('')}</select></label>${playerField}${extra}<label>Privacy<select name="privacy"><option value="public" ${lobby.privacy === 'public' ? 'selected' : ''}>Pubblica</option><option value="private" ${lobby.privacy === 'private' ? 'selected' : ''}>Privata</option></select></label><button class="btn ghost" type="submit">Salva impostazioni</button></form><button class="btn primary" data-start-lobby="${lobby.id}" ${ready ? '' : 'disabled'}>${ready ? 'Avvia partita' : `Servono ${game?.players.min || 2} giocatori`}</button>` : '<p class="muted">L’host avvierà la partita quando tutti saranno pronti.</p>'}</aside>`;
}
function renderCreateLobbyModal() {
  if (!state.createLobbyOpen) return '';
  const selected = state.games.find(game => game.id === state.createLobbyGameId) || state.games[0];
  if (!selected) return '';
  const min = selected.players.min; const max = selected.players.max;
  const playerField = min === max ? `<label>Giocatori richiesti<input value="${max}" disabled><input type="hidden" name="maxPlayers" value="${max}"></label>` : `<label>Numero massimo giocatori<input name="maxPlayers" type="number" min="${min}" max="${max}" value="${max}" required></label>`;
  const extra = selected.id === 'battaglia-navale' ? `<label>Modalità<select name="mode" id="create-battle-mode"><option value="classic" ${state.battleLobbyMode === 'classic' ? 'selected' : ''}>Classica · set personalizzabile</option><option value="plus" ${state.battleLobbyMode === 'plus' ? 'selected' : ''}>Plus · deck e poteri</option></select></label>${renderBattleLobbySettings(state.battleLobbyMode, { boardSize: 10 })}` : renderGameLobbySettings(selected.id);
  return `<div class="modal-backdrop"><section class="modal panel" role="dialog" aria-modal="true" aria-labelledby="lobby-modal-title"><div class="row"><div><p class="eyebrow">nuova stanza</p><h2 id="lobby-modal-title">Crea lobby</h2></div><button class="btn ghost small" data-close-modal>Chiudi</button></div><form id="create-lobby-form" class="form"><label>Gioco<select name="gameId" id="create-game-select">${state.games.map(game => `<option value="${game.id}" ${game.id === selected.id ? 'selected' : ''}>${escapeHtml(game.name)} · ${game.players.min}-${game.players.max} giocatori</option>`).join('')}</select></label>${playerField}${extra}<label>Privacy<select name="privacy"><option value="public">Pubblica</option><option value="private">Privata</option></select></label><div id="lobby-form-error" class="error"></div><button class="btn primary" type="submit">Crea lobby</button></form></section></div>`;
}
function renderMatch() {
  if (!state.match) return '<div class="empty">Nessuna partita selezionata.</div>';
  if (state.match.gameId === 'tris') return renderTrisMatch();
  if (state.match.gameId === 'battaglia-navale') return renderBattleshipMatch();
  if (state.match.gameId === 'uno') return renderUnoMatch();
  if (state.match.gameId === 'bingo') return renderBingoMatch();
  if (state.match.gameId === 'wordle-coop' || state.match.gameId === 'wordle-competitivo') return renderWordleMatch();
  return renderForzaMatch();
}
function matchHeader(title, subtitle, gameId) {
  return `<div class="section-header"><div><p class="eyebrow">partita live · ${escapeHtml(gameId)}</p><h1>${escapeHtml(title)}</h1><p class="muted">${escapeHtml(subtitle)}</p></div><button class="btn danger" data-leave-match>${state.match.status === 'FINISHED' ? 'Torna alle lobby' : 'Abbandona partita'}</button></div>`;
}
function renderForzaMatch() {
  const match = state.match; const gameState = match.state; const me = state.user.id; const myPlayer = gameState?.players?.find(p => p.id === me); const turnName = gameState?.players?.find(p => p.id === gameState.turn)?.id === me ? 'È il tuo turno' : 'Turno avversario';
  return `<section>${matchHeader('Forza 4', gameState?.winner ? (gameState.winner === me ? 'Hai vinto!' : 'Partita terminata') : gameState?.draw ? 'Pareggio' : turnName, match.gameId)}<div class="match-layout"><div class="panel"><div id="board-root"></div><p class="muted" style="margin:16px 0 0">Pedina: <span class="pill">${myPlayer?.color || '—'}</span> · Passa sopra una colonna per vedere l’anteprima, poi clicca.</p></div><div class="panel"><p class="eyebrow">partita e lobby</p><h2>Forza 4</h2><div class="list"><div class="list-item"><span class="muted">Prossimo gioco</span><strong>Forza 4</strong></div><div class="list-item"><span class="muted">Giocatori</span><strong>${match.players?.length || 0}/2</strong></div><div class="list-item"><span class="muted">Versione</span><strong>${escapeHtml(match.gameVersion)}</strong></div><div class="list-item"><span class="muted">Stato</span><span class="pill success">${match.status}</span></div><div class="list-item"><span class="muted">Sequenza</span><strong>${match.sequence || 0}</strong></div></div><p class="muted">La lobby è stata bloccata all’avvio: le sue impostazioni non cambiano durante la partita.</p></div></div></section>`;
}
function renderTrisMatch() {
  const gameState = state.match.state; const me = state.user.id; const mePlayer = gameState.players?.find(player => player.id === me); const winnerPlayer = gameState.players?.find(player => player.id === gameState.winner); const status = gameState.winner ? (gameState.winner === me ? 'Hai vinto!' : `${winnerPlayer?.id || 'L’avversario'} ha vinto`) : gameState.draw ? 'Pareggio' : gameState.turn === me ? 'È il tuo turno' : 'Turno avversario'; const statusClass = gameState.winner ? gameState.winner === me ? 'match-win' : 'match-loss' : '';
  const linePoints = { '0,1,2': '16,16 84,16', '3,4,5': '16,50 84,50', '6,7,8': '16,84 84,84', '0,3,6': '16,16 16,84', '1,4,7': '50,16 50,84', '2,5,8': '84,16 84,84', '0,4,8': '16,16 84,84', '2,4,6': '84,16 16,84' }; const points = gameState.winningLine ? linePoints[gameState.winningLine.join(',')] : '';
  return `<section>${matchHeader('Tris', status, state.match.gameId)}<div class="match-layout"><div class="panel"><div class="tris-board-wrap"><div id="tris-board-root" class="tris-board">${gameState.board.map((mark, index) => `<button class="tris-cell ${mark || ''}" data-tris-cell="${index}" aria-label="Casella ${index + 1}">${mark || ''}</button>`).join('')}</div>${points ? `<svg class="tris-win-overlay" viewBox="0 0 100 100" preserveAspectRatio="none"><line x1="${points.split(' ')[0].split(',')[0]}" y1="${points.split(' ')[0].split(',')[1]}" x2="${points.split(' ')[1].split(',')[0]}" y2="${points.split(' ')[1].split(',')[1]}" /></svg>` : ''}</div><p class="muted" style="margin-top:16px">Il tuo simbolo: <span class="pill">${mePlayer?.mark || '—'}</span></p>${gameState.winner ? `<p class="winner-message ${statusClass}">${escapeHtml(status)}</p>` : ''}</div><div class="panel"><p class="eyebrow">partita e lobby</p><h2>Tris classico</h2><div class="list"><div class="list-item"><span class="muted">Giocatori</span><strong>2/2</strong></div><div class="list-item"><span class="muted">Stato</span><span class="pill success">${state.match.status}</span></div><div class="list-item"><span class="muted">Sequenza</span><strong>${state.match.sequence || 0}</strong></div></div></div></div></section>`;
}
function unoCardLabel(card) { return card.value === 'skip' ? '⊘' : card.value === 'reverse' ? '↺' : card.value === 'draw2' ? '+2' : card.value === 'wild4' ? '+4' : card.value === 'wild' ? '★' : card.value; }
function renderUnoMatch() { const gameState = state.match.state; const me = state.user.id; const status = gameState.winner ? (gameState.winner === me ? 'Hai vinto!' : 'Partita terminata') : gameState.turn === me ? 'È il tuo turno' : 'Turno avversario'; return `<section>${matchHeader('Uno', status, state.match.gameId)}<div class="match-layout"><div class="panel uno-table"><div class="uno-top"><div><p class="eyebrow">carta in cima</p><button class="uno-card large ${gameState.topCard?.color || 'wild'}">${unoCardLabel(gameState.topCard || { value: '?' })}</button></div><div><p class="eyebrow">colore attuale</p><span class="uno-color ${gameState.currentColor || 'wild'}">${gameState.currentColor || '—'}</span><p class="muted">${gameState.pendingDraw ? `Pesca +${gameState.pendingDraw}` : gameState.modeName}</p></div></div><div class="section"><p class="eyebrow">la tua mano · ${gameState.hand.length} carte</p><div class="uno-hand">${gameState.hand.map(card => `<button class="uno-card ${card.color}" data-uno-card="${card.id}" ${gameState.turn === me && !gameState.winner ? '' : 'disabled'}>${unoCardLabel(card)}</button>`).join('')}</div><div class="row" style="margin-top:16px"><button class="btn ghost" data-uno-draw ${gameState.turn === me && !gameState.winner ? '' : 'disabled'}>Pesca carta</button><button class="btn primary" data-uno-call ${gameState.hand.length <= 2 && gameState.turn === me ? '' : 'disabled'}>UNO!</button></div></div></div><div class="panel"><p class="eyebrow">giocatori · ${escapeHtml(gameState.modeName)}</p><div class="list">${gameState.players.map(player => `<div class="list-item"><span>${escapeHtml(player.id)}${player.id === gameState.turn ? ' · turno' : ''}</span><strong>${player.cardCount} carte${player.calledUno ? ' · UNO!' : ''}</strong></div>`).join('')}</div><p class="muted">Modalità: ${escapeHtml(gameState.modeName)}. Le modalità Stack e Caos cambiano le regole delle carte speciali.</p></div></div></section>`; }
function renderBingoMatch() { const gameState = state.match.state; const me = state.user.id; const status = gameState.winner ? (gameState.winner === me ? 'Hai fatto BINGO!' : 'Partita terminata') : gameState.turn === me ? 'Scegli un numero' : 'Turno avversario'; const marked = new Set(gameState.marked || []); return `<section>${matchHeader('Bingo', status, state.match.gameId)}<div class="match-layout"><div class="panel"><p class="eyebrow">la tua scheda · ${gameState.calledNumbers.length} numeri chiamati</p><div class="bingo-board">${gameState.board.map(number => `<button class="bingo-cell ${marked.has(number) ? 'marked' : ''} ${gameState.calledNumbers.includes(number) ? 'called' : ''}" data-bingo-number="${number}" ${gameState.turn === me && !gameState.winner ? '' : 'disabled'}>${number}</button>`).join('')}</div><p class="muted">Ogni numero scelto viene marcato su tutte le schede.</p></div><div class="panel"><p class="eyebrow">classifica BINGO</p><div class="list">${gameState.players.map(player => `<div class="list-item"><div><strong>${escapeHtml(matchPlayerName(player.id))}</strong><div class="bingo-word">${'BINGO'.split('').map((letter, index) => `<span class="${index < player.progress ? 'done' : ''}">${index < player.progress ? letter : '_'}</span>`).join('')}</div></div><strong>${player.progress}/5</strong></div>`).join('')}</div><p class="muted">Le lettere si sbloccano ogni volta che completi una riga, colonna o diagonale.</p></div></div></section>`; }
function wordleBoard(board, index) { const rows = board.guesses.map(entry => `<div class="wordle-row">${entry.guess.split('').map((letter, cell) => `<span class="wordle-cell ${entry.evaluation[cell]}">${letter}</span>`).join('')}</div>`).join(''); const resultLabel = board.solved ? ' · risolta' : board.failed ? ' · non indovinata' : ''; const solution = board.target ? `<p class="wordle-solution">Soluzione: <strong>${escapeHtml(board.target)}</strong></p>` : ''; return `<div class="wordle-board"><p class="eyebrow">Parola ${index + 1}${resultLabel}</p>${rows}${Array.from({ length: Math.max(0, 6 - board.guesses.length) }, () => '<div class="wordle-row">' + '<span class="wordle-cell empty"></span>'.repeat(5) + '</div>').join('')}${solution}</div>`; }
function renderWordleMatch() { const gameState = state.match.state; const me = state.user.id; const mePlayer = gameState.players.find(player => player.id === me); const endedForMe = Boolean(gameState.winner || gameState.draw || gameState.lost || mePlayer?.finished || mePlayer?.lost); const status = gameState.lost ? 'Hai perso: tentativi esauriti' : mePlayer?.lost ? 'Hai esaurito i tentativi' : gameState.winner ? (gameState.winner === me ? 'Hai vinto!' : 'Partita terminata') : gameState.draw ? 'Pareggio' : gameState.matchMode === 'time' ? `${gameState.secondsLeft}s rimasti` : 'Indovina tutte le parole'; return `<section>${matchHeader(gameState.variant === 'coop' ? 'Wordle cooperativo' : 'Wordle competitivo', status, state.match.gameId)}<div class="match-layout"><div class="panel"><div class="wordle-grid">${gameState.boards.map((board, index) => wordleBoard(board, index)).join('')}</div><form id="wordle-form" class="wordle-form ${endedForMe ? 'wordle-form-ended' : ''}"><input name="guess" maxlength="5" minlength="5" placeholder="${endedForMe ? 'Tentativi terminati' : 'Inserisci una parola di 5 lettere'}" autocomplete="off" required ${endedForMe ? 'disabled' : ''}><button class="btn primary" ${endedForMe ? 'disabled' : ''}>${endedForMe ? 'Partita terminata' : 'Invia tentativo'}</button></form><p class="muted">${gameState.variant === 'coop' ? 'Il tentativo viene applicato a tutte le parole contemporaneamente. Hai 6 tentativi.' : 'Ogni giocatore ha i propri tabelloni e 6 tentativi per parola.'}</p></div><div class="panel"><p class="eyebrow">giocatori</p><div class="list">${gameState.players.map(player => `<div class="list-item"><span>${escapeHtml(matchPlayerName(player.id))}</span><strong>${player.score}/${gameState.wordCount}${player.lost ? ' · sconfitto' : player.finished ? ' · finito' : ''}</strong></div>`).join('')}</div></div></div></section>`; }
function navalCellClass(cell) { if (!cell) return ''; if (cell.type === 'hit') return 'hit'; if (cell.type === 'miss') return 'miss'; if (cell.type === 'revealed') return 'revealed'; if (cell.type === 'sunk') return `sunk ship ship-${cell.shipType || 'unknown'}`; if (cell.type === 'obstacle') return `obstacle obstacle-${cell.obstacle || 'rock'}`; return `ship ship-${cell.type}${cell.hit ? ' ship-hit' : ''}${cell.sunk ? ' sunk' : ''}${cell.revealed ? ' revealed' : ''}`; }
function shipSvg(ship) {
  const shape = ship.shape || [[0, 0]]; const columns = Math.max(...shape.map(([, col]) => col)) + 1; const rows = Math.max(...shape.map(([row]) => row)) + 1; const safeId = String(ship.id).replace(/[^a-z0-9_-]/gi, '-'); const gradientId = `ship-gradient-${safeId}`; const pieces = shape.map(([row, col], index) => { const x = col * 34 + 2; const y = row * 28 + 3; const first = index === 0; const last = index === shape.length - 1; const single = first && last; const bow = last ? `M${x + 2} ${y + 4} H${x + 23} L${x + 31} ${y + 12} L${x + 23} ${y + 20} H${x + 2} Z` : `M${x + 2} ${y + 4} H${x + 28} Q${x + 32} ${y + 12} ${x + 28} ${y + 20} H${x + 2} Q${x - 2} ${y + 12} ${x + 2} ${y + 4} Z`; const stern = first && !last ? `<path d="M${x + 2} ${y + 4} Q${x - 2} ${y + 12} ${x + 2} ${y + 20}" class="ship-svg-stern"/>` : ''; const porthole = single ? `<circle cx="${x + 16}" cy="${y + 12}" r="4" class="ship-svg-window"/>` : `<circle cx="${x + 15}" cy="${y + 12}" r="3" class="ship-svg-window"/>`; return `<g class="ship-svg-piece ${first ? 'stern' : ''} ${last ? 'bow' : ''}"><path d="${last ? bow : bow}" class="ship-svg-hull"/>${stern}${porthole}${last ? `<path d="M${x + 11} ${y + 7} L${x + 18} ${y + 7}" class="ship-svg-deck"/>` : ''}</g>`; }).join(''); return `<svg class="ship-svg" viewBox="0 0 ${columns * 34} ${rows * 28}" role="img" aria-label="${escapeHtml(ship.name)}"><defs><linearGradient id="${gradientId}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#ffffff" stop-opacity=".9"/><stop offset=".28" stop-color="var(--ship-color)"/><stop offset="1" stop-color="#07121d"/></linearGradient></defs>${pieces.replaceAll('class="ship-svg-hull"', `class="ship-svg-hull" fill="url(#${gradientId})"`)}</svg>`;
}
function shipColor(ship) { const palette = ['#65caff', '#7fe7c4', '#9a7cff', '#ff82c8', '#ff8b69', '#ffb25e', '#ffd166', '#9ff2a6', '#6c8cff']; const hash = String(ship.id || ship.name).split('').reduce((sum, char) => sum + char.charCodeAt(0), 0); return palette[hash % palette.length]; }
function powerGraphic(pattern, powerId = '') { const glyphs = { square3: '<rect x="3" y="3" width="18" height="18" rx="3"/>', square9: '<rect x="3" y="3" width="18" height="18" rx="3"/><path d="M12 3v18M3 12h18"/>', line3: '<path d="M4 12h16M7 8v8M12 6v12M17 8v8"/>', line5: '<path d="M2 12h20M5 8v8M9 6v12M15 6v12M19 8v8"/>', cross5: '<path d="M12 3v18M3 12h18"/>', cross7: '<path d="M12 2v20M2 12h20M6 6l12 12M18 6L6 18"/>', cross9: '<path d="M12 2v20M2 12h20"/>', ring8: '<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="2"/>', diamond9: '<path d="M12 2l10 10-10 10L2 12 12 2z"/><circle cx="12" cy="12" r="2"/>', corners4: '<path d="M5 5h4M5 5v4M19 5h-4M19 5v4M5 19h4M5 19v-4M19 19h-4M19 19v-4"/>', diagonal5: '<path d="M4 4l16 16M20 4L4 20"/>', diagonal7: '<path d="M3 3l18 18M21 3L3 21M12 3v18"/>', star8: '<path d="M12 2v20M2 12h20M5 5l14 14M19 5L5 19"/>', knight8: '<path d="M7 5l-3 4 4 3-3 4 4 3 3-4 4 3 3-4-4-3 3-4-4-3-3 4z"/>', triad3: '<path d="M12 4l7 14H5z"/>', fan7: '<path d="M4 20l8-16 8 16M7 14h10M6 18h12"/>', wave7: '<path d="M2 15c3-8 5 8 8 0s5 8 8 0 3 0 4-3"/>', halo12: '<circle cx="12" cy="12" r="9" stroke-dasharray="3 3"/><circle cx="12" cy="12" r="2"/>' }; const hash = String(powerId || pattern).split('').reduce((sum, char) => sum + char.charCodeAt(0), 0); const angle = hash % 360; const accentX = 4 + (hash % 16); const accentY = 4 + ((hash * 3) % 16); const hue = (hash * 29) % 360; return `<svg viewBox="0 0 24 24" aria-hidden="true" style="color:hsl(${hue} 90% 72%)"><g transform="rotate(${angle} 12 12)">${glyphs[pattern] || glyphs.square3}<circle cx="${accentX}" cy="${accentY}" r="1.2" fill="currentColor" stroke="none"/></g></svg>`; }
function shipToken(ship, { draggable = true, deckShipId = '', shipId = '', selectAction = '', selected = false, addToDeck = false, statusText = '' } = {}) {
  if (!ship) return '';
  const shape = ship.shape || [[0, 0]];
  const power = ship.ability || ship.specialShot; const ability = power ? `<span class="ship-ability"><span class="power-gfx ${ship.ability ? 'power-ability' : 'power-special'}">${powerGraphic(power.pattern, power.id)}</span>${escapeHtml(power.name)}</span>` : '';
  const dragAttributes = draggable ? `draggable="true" data-drag-ship data-ship-type="${ship.id}" data-deck-ship-id="${deckShipId}" data-ship-id="${shipId}" title="Trascina questa card"` : '';
  const selectAttributes = selectAction ? `data-ship-select="${selectAction}" data-select-ship-type="${ship.id}" data-select-deck-ship="${deckShipId}" data-select-ship-id="${shipId}" tabindex="0" role="button" aria-pressed="${selected ? 'true' : 'false'}"` : '';
  const deckAttribute = addToDeck ? `data-add-deck="${ship.id}"` : '';
  return `<article class="ship-card ship-${ship.id} ${selected ? 'selected' : ''} ${selectAction ? 'ship-selectable' : ''}" style="--ship-color:${shipColor(ship)}" ${dragAttributes} ${selectAttributes} ${deckAttribute}><div class="ship-art">${shipSvg(ship)}</div><div class="ship-copy"><strong>${escapeHtml(ship.name)}</strong><span>${ship.size} quadratini · ${ship.class}</span>${ability}${statusText ? `<span class="ship-status">${escapeHtml(statusText)}</span>` : ''}</div></article>`;
}
function renderNavalShipOverlays(ships = [], shipTypes = []) { return ships.map(ship => { const type = shipTypes.find(item => item.id === ship.typeId); if (!type) return ''; const absoluteCells = previewShipCells(type, ship.row, ship.col, ship.orientation, ship.mirror); const minRow = Math.min(...absoluteCells.map(cell => cell.row)); const minCol = Math.min(...absoluteCells.map(cell => cell.col)); const maxRow = Math.max(...absoluteCells.map(cell => cell.row)); const maxCol = Math.max(...absoluteCells.map(cell => cell.col)); const localShape = absoluteCells.map(cell => [cell.row - minRow, cell.col - minCol]); const displayType = { ...type, id: `board-${ship.id}`, shape: localShape }; const hit = (ship.hits || []).length > 0; const sunk = ship.sunk === true || (ship.hits || []).length >= type.size; return `<div class="naval-ship-overlay ${hit ? 'has-hit' : ''} ${sunk ? 'has-sunk' : ''}" style="--ship-row:${minRow};--ship-col:${minCol};--ship-cols:${maxCol - minCol + 1};--ship-rows:${maxRow - minRow + 1};--ship-color:${shipColor(type)}">${shipSvg(displayType)}</div>`; }).join(''); }
function renderNavalGrid(board, { interactive = false, dropTarget = false, id = '', ships = [], shipTypes = [] } = {}) { if (!board) return '<div class="empty">Tabellone non ancora disponibile.</div>'; const size = board.length; return `<div ${id ? `id="${id}"` : ''} class="naval-board ${dropTarget ? 'naval-drop-target' : ''}" style="--naval-size:${size}">${board.flatMap((row, r) => row.map((cell, c) => `<button class="naval-cell ${navalCellClass(cell)}" data-naval-row="${r}" data-naval-col="${c}" ${interactive ? '' : dropTarget ? '' : 'disabled'} aria-label="Riga ${r + 1}, colonna ${c + 1}"></button>`)).join('')}${renderNavalShipOverlays(ships, shipTypes)}</div>`; }
function previewShipCells(type, row, col, orientation, mirror = false) {
  const mirrored = mirror ? type.shape.map(([shipRow, shipCol]) => [shipRow, -shipCol]) : type.shape;
  const rotated = orientation === 'V' ? mirrored.map(([shipRow, shipCol]) => [shipCol, -shipRow]) : mirrored;
  const minRow = Math.min(...rotated.map(([shipRow]) => shipRow));
  const minCol = Math.min(...rotated.map(([, shipCol]) => shipCol));
  return rotated.map(([shipRow, shipCol]) => ({ row: row + shipRow - minRow, col: col + shipCol - minCol }));
}
function clearShipPreview(board) { board?.querySelectorAll('.drop-preview-valid, .drop-preview-invalid, .shot-preview, .shot-preview-invalid').forEach(cell => cell.classList.remove('drop-preview-valid', 'drop-preview-invalid', 'shot-preview', 'shot-preview-invalid')); }
function showShipPreview(board, gameState, draggedShip, row, col, orientation, mirror = false) {
  clearShipPreview(board);
  const type = gameState.shipTypes.find(ship => ship.id === draggedShip.typeId);
  if (!type) return;
  const cells = previewShipCells(type, row, col, orientation, mirror);
  const valid = cells.every(cell => cell.row >= 0 && cell.col >= 0 && cell.row < gameState.size && cell.col < gameState.size && !gameState.ownBoard[cell.row][cell.col]);
  cells.forEach(cell => board.querySelector(`[data-naval-row="${cell.row}"][data-naval-col="${cell.col}"]`)?.classList.add(valid ? 'drop-preview-valid' : 'drop-preview-invalid'));
}
function shotPatternCells(row, col, pattern, orientation = 'H', mirror = false) {
  let offsets; if (pattern === 'line3' || pattern === 'line5') { const radius = pattern === 'line5' ? 2 : 1; offsets = Array.from({ length: radius * 2 + 1 }, (_, index) => orientation === 'V' ? [index - radius, 0] : [0, index - radius]); } else if (pattern === 'cross5') offsets = [[0, 0], [-1, 0], [1, 0], [0, -1], [0, 1]]; else if (pattern === 'cross7') offsets = [[0, 0], [-1, 0], [1, 0], [0, -1], [0, 1], [-2, 0], [2, 0]]; else if (pattern === 'cross9') offsets = [[0, 0], [-1, 0], [1, 0], [-2, 0], [2, 0], [-3, 0], [3, 0], [-4, 0], [4, 0]]; else if (pattern === 'square4') offsets = [[0, 0], [0, 1], [1, 0], [1, 1]]; else if (pattern === 'square3' || pattern === 'square9' || pattern === 'rose9') offsets = Array.from({ length: 9 }, (_, index) => [Math.floor(index / 3) - 1, (index % 3) - 1]); else if (pattern === 'rose5') offsets = [[0, 0], [-1, -1], [-1, 1], [1, -1], [1, 1]]; else if (pattern === 'diamond9') offsets = [[0, 0], [-1, 0], [1, 0], [0, -1], [0, 1], [-1, -1], [-1, 1], [1, -1], [1, 1]]; else if (pattern === 'ring8') offsets = [[-1, -1], [-1, 0], [-1, 1], [0, -1], [0, 1], [1, -1], [1, 0], [1, 1]]; else if (pattern === 'corners4') offsets = [[-1, -1], [-1, 1], [1, -1], [1, 1]]; else if (pattern === 'diagonal5') offsets = [[0, 0], [-1, -1], [1, 1], [-1, 1], [1, -1]]; else if (pattern === 'diagonal7') offsets = [[0, 0], [-3, -3], [-2, -2], [-1, -1], [1, 1], [2, 2], [3, 3]]; else if (pattern === 'star8' || pattern === 'knight8') offsets = [[-2, -1], [-2, 1], [-1, -2], [-1, 2], [1, -2], [1, 2], [2, -1], [2, 1]]; else if (pattern === 'triad3') offsets = [[0, 0], [-1, 1], [1, 1]]; else if (pattern === 'fan7') offsets = [[0, 0], [0, 1], [0, 2], [1, 1], [2, 0], [2, 1], [2, 2]]; else if (pattern === 'wave7') offsets = [[0, -3], [1, -2], [-1, -1], [0, 0], [1, 1], [-1, 2], [0, 3]]; else if (pattern === 'halo12') offsets = [[-2, -1], [-2, 0], [-2, 1], [-1, -2], [-1, 2], [0, -2], [0, 2], [1, -2], [1, 2], [2, -1], [2, 0], [2, 1]]; else offsets = [[0, 0]];
  return offsets.map(([deltaRow, deltaCol]) => ({ row: row + deltaRow, col: col + (mirror ? -deltaCol : deltaCol) }));
}
function showShotPreview(board, gameState, ship, mode, row, col, orientation, mirror) {
  clearShipPreview(board); const type = gameState.shipTypes.find(item => item.id === ship?.typeId); if (!type) return;
  const pattern = mode === 'ability' ? type.ability?.pattern : mode === 'special' ? type.specialShot?.pattern : null; const cells = pattern ? shotPatternCells(row, col, pattern, orientation, mirror) : [{ row, col }]; const valid = cells.every(cell => cell.row >= 0 && cell.col >= 0 && cell.row < gameState.size && cell.col < gameState.size); cells.forEach(cell => board.querySelector(`[data-naval-row="${cell.row}"][data-naval-col="${cell.col}"]`)?.classList.add(valid ? 'shot-preview' : 'shot-preview-invalid'));
}
function renderShipLibrary(gameState, allowedIds = null, excludedIds = new Set()) { const ships = gameState.shipTypes.filter(ship => ship.availability !== 'classic' && (!allowedIds || allowedIds.includes(ship.id)) && !excludedIds.has(ship.id)); return `<div class="ship-library"><div class="ship-library-head"><strong>${ships.length} navi disponibili</strong><span>Scorri il catalogo per vedere tutte le carte.</span></div>${['small', 'medium', 'large'].map(category => { const group = ships.filter(ship => ship.category === category); if (!group.length) return ''; const label = category === 'small' ? 'navi piccole' : category === 'medium' ? 'navi medie' : 'navi grandi'; return `<section class="ship-category"><p class="eyebrow">${label} · ${group.length}</p><div class="ship-card-grid">${group.map(ship => shipToken(ship, { draggable: true, selectAction: 'deck', addToDeck: true })).join('')}</div></section>`; }).join('')}</div>`; }
function navalActivityText(gameState) { const activity = gameState.lastAction; if (!activity) return ''; const reveals = activity.reveals || []; const results = activity.results || []; const revealedText = reveals.map(reveal => { const content = reveal.content || {}; const found = content.obstacle ? content.obstacle === 'rock' ? 'Roccia' : 'Isola' : content.type === 'revealed' ? 'Acqua' : gameState.shipTypes.find(ship => ship.id === content.type)?.name || 'Nave'; return `Riga ${reveal.row + 1}, colonna ${reveal.col + 1}: ${found}`; }); const shotText = results.map(result => `Riga ${result.row + 1}, colonna ${result.col + 1}: ${result.result === 'hit' ? 'colpito' : 'acqua'}`); return [...revealedText, ...shotText].join(' · '); }
function renderBattleshipMatch() {
  const gameState = state.match.state; const me = state.user.id; const currentPlayer = gameState.players.find(player => player.id === me); const turnText = gameState.phase === 'DECK_BUILD' ? 'Trascina le navi nel tuo deck.' : gameState.phase === 'SETUP' ? (gameState.mode === 'classic' ? 'Posiziona direttamente la flotta sul tabellone.' : 'Ora posiziona il deck sul tabellone.') : gameState.winner ? (gameState.winner === me ? 'Hai vinto!' : 'Partita terminata') : gameState.turn === me ? 'È il tuo turno' : 'Turno avversario';
  if (gameState.phase === 'DECK_BUILD') {
    const selectedIds = new Set(gameState.deck.map(item => item.typeId)); const spent = gameState.deck.reduce((sum, item) => sum + (gameState.shipTypes.find(ship => ship.id === item.typeId)?.cost || 0), 0);
    return `<section>${matchHeader('Battaglia Navale', turnText, state.match.gameId)}<div class="match-layout naval-layout"><div class="panel"><p class="eyebrow">flotta Plus · card disponibili</p><h2>Scegli le navi</h2><p class="muted">Clicca una card oppure trascinala nel deck. Ogni nave scelta sparisce dalla flotta.</p>${renderShipLibrary(gameState, null, selectedIds)}</div><div class="panel"><p class="eyebrow">il tuo deck · ${spent}/${gameState.deckBudget} punti · minimo ${gameState.minDeckShips} navi</p><div id="deck-dropzone" class="deck-dropzone">${gameState.deck.length ? `<div class="ship-card-grid">${gameState.deck.map(item => `<div class="ship-deck-item">${shipToken(gameState.shipTypes.find(ship => ship.id === item.typeId), { draggable: false, deckShipId: item.id })}<button class="btn danger small" data-remove-deck="${item.id}">Rimuovi</button></div>`).join('')}</div>` : '<span>Clicca una carta o trascinala qui</span>'}</div><p class="muted">Massimo 2 navi piccole e 1 nave grande. La descrizione di ogni card indica abilità o colpo speciale.</p><button class="btn primary" data-ready-deck ${currentPlayer.deckReady ? 'disabled' : ''}>Conferma deck</button></div></div></section>`;
  }
  if (gameState.phase === 'SETUP') {
    const legacyFleet = ['carrier', 'battleship', 'cruiser', 'submarine', 'destroyer'].map((typeId, index) => ({ id: `legacy-${index}`, typeId })); const classicFleet = Array.isArray(gameState.fleet) ? gameState.fleet : legacyFleet; const placedIds = new Set(gameState.ships.map(ship => ship.id)); const available = gameState.mode === 'plus' ? (gameState.deck || []).filter(ship => !placedIds.has(ship.id)).map(item => ({ ...gameState.shipTypes.find(ship => ship.id === item.typeId), instanceId: item.id })) : classicFleet.filter(item => !placedIds.has(item.id)).map(item => ({ ...gameState.shipTypes.find(ship => ship.id === item.typeId), instanceId: item.id }));
    const fleetIsLegacy = !Array.isArray(gameState.fleet); const fleetSetName = gameState.fleetSets?.[gameState.fleetSet]?.name || gameState.fleetSet || 'classica'; const fleetCount = gameState.mode === 'plus' ? (gameState.deck || []).length : classicFleet.length;
    const selectedPlacementId = state.navalSelectedShipId; const placementCards = available.filter(Boolean).map(ship => shipToken(ship, { shipId: fleetIsLegacy ? '' : ship.instanceId, deckShipId: gameState.mode === 'plus' ? ship.instanceId : '', selectAction: 'placement', selected: selectedPlacementId === (gameState.mode === 'plus' ? ship.instanceId : ship.instanceId) })).join('');
    return `<section>${matchHeader('Battaglia Navale', turnText, state.match.gameId)}<div class="setup-toolbar"><strong>Anteprima posizione</strong><span class="kbd-help"><kbd>R</kbd> ruota · <kbd>T</kbd> specchia</span><span class="transform-state">${state.navalOrientation === 'V' ? 'Verticale' : 'Orizzontale'} · ${state.navalMirror ? 'specchiata' : 'normale'}</span><span class="muted">Seleziona una card, poi passa sul tabellone o trascinala. Clicca una cella per piazzarla.</span></div><div class="naval-setup-layout"><div class="panel naval-setup-board"><p class="eyebrow">il tuo tabellone · ${gameState.size}×${gameState.size}</p>${renderNavalGrid(gameState.ownBoard, { dropTarget: true, id: 'own-naval-board', ships: gameState.ships, shipTypes: gameState.shipTypes })}<div class="section"><p class="muted">Navi piazzate: ${gameState.ships.length}/${fleetCount}</p>${gameState.ships.map(ship => `<div class="lobby-player"><span class="ship-mini ship-${ship.typeId}"></span><strong>${escapeHtml(gameState.shipTypes.find(type => type.id === ship.typeId)?.name || ship.typeId)}</strong><button class="btn danger small" data-remove-ship="${ship.id}">Rimuovi</button></div>`).join('')}<button class="btn primary" data-ready-fleet ${currentPlayer.ready ? 'disabled' : ''}>Conferma flotta</button></div></div><div class="panel naval-setup-deck"><p class="eyebrow">${gameState.mode === 'classic' ? `set ${escapeHtml(fleetSetName)}` : 'navi del tuo deck'}</p><div class="ship-card-grid naval-placement-deck">${placementCards}</div><p class="muted">Scegli una carta qui sotto, poi trascinala o seleziona la casella di destinazione sul tabellone.</p></div></div></section>`;
  }
  const selectedShipId = gameState.ships.some(ship => ship.id === state.navalSelectedShipId) ? state.navalSelectedShipId : gameState.ships[0]?.id; state.navalSelectedShipId = selectedShipId || '';
  const selectedShip = gameState.ships.find(ship => ship.id === selectedShipId); const selectedType = gameState.shipTypes.find(type => type.id === selectedShip?.typeId); const selectedMode = gameState.mode === 'plus' && ['normal', 'ability', 'special'].includes(state.navalSelectedMode) ? state.navalSelectedMode : 'normal';
  const shotCards = gameState.ships.map(ship => { const type = gameState.shipTypes.find(item => item.id === ship.typeId); const cooldown = (ship.cooldown || []).length; return shipToken(type, { draggable: false, shipId: ship.id, selectAction: 'shot', selected: ship.id === selectedShipId, statusText: cooldown >= 3 ? 'In ricarica' : 'Pronta' }); }).join('');
  const modes = [`<button class="shot-mode ${selectedMode === 'normal' ? 'active' : ''}" data-shot-mode="normal">Colpo singolo</button>`]; if (gameState.abilitiesEnabled && selectedType?.ability) modes.push(`<button class="shot-mode ${selectedMode === 'ability' ? 'active' : ''}" data-shot-mode="ability">✦ ${escapeHtml(selectedType.ability.name)}</button>`); if (gameState.specialShotsEnabled && selectedType?.specialShot) modes.push(`<button class="shot-mode ${selectedMode === 'special' ? 'active' : ''}" data-shot-mode="special">◆ ${escapeHtml(selectedType.specialShot.name)}</button>`);
  const shotControl = gameState.mode === 'plus' ? `<div class="shot-controls"><p class="eyebrow">scegli la nave da usare</p><div class="ship-card-grid shot-card-grid">${shotCards}</div><div class="shot-mode-row">${modes.join('')}</div><p class="transform-state">${state.navalOrientation === 'V' ? 'Colpo verticale' : 'Colpo orizzontale'} · ${state.navalMirror ? 'specchiato' : 'normale'} · <kbd>R</kbd> ruota · <kbd>T</kbd> specchia</p><p class="muted">Ogni turno puoi usare una sola nave. Una nave torna pronta dopo tre navi differenti.</p></div>` : `<div class="shot-controls"><p class="eyebrow">scegli la nave da usare</p><div class="ship-card-grid shot-card-grid">${shotCards}</div><p class="transform-state">Colpo classico su una casella · <kbd>R</kbd> ruota · <kbd>T</kbd> specchia</p></div>`;
  const activity = navalActivityText(gameState); const bridge = gameState.lastAction ? `<div class="naval-attack-bridge" aria-hidden="true">${Array.from({ length: Math.min(5, Math.max(1, (gameState.lastAction.results || []).length)) }, (_, index) => `<span style="--shot-index:${index}"></span>`).join('')}</div>` : '';
  return `<section>${matchHeader('Battaglia Navale', turnText, state.match.gameId)}<div class="panel naval-duel ${gameState.lastAction ? 'has-activity' : ''}"><div class="naval-side"><p class="eyebrow">tabellone nemico · ${gameState.size}×${gameState.size}</p>${renderNavalGrid(gameState.opponentBoard, { interactive: gameState.turn === me && !gameState.winner, id: 'opponent-naval-board', ships: gameState.sunkShips || [], shipTypes: gameState.shipTypes })}<div class="naval-legend"><span><i class="legend-hit"></i>Colpito</span><span><i class="legend-miss"></i>Acqua / già tentato</span><span><i class="legend-revealed"></i>Rivelato</span><span><i class="legend-sunk"></i>Affondata</span></div><p class="muted">Le navi e gli ostacoli nemici restano nascosti; una nave appare quando è completamente affondata.</p>${activity ? `<div class="naval-activity"><strong>Ultimo lancio</strong><span>${escapeHtml(activity)}</span></div>` : ''}${shotControl}</div><div class="naval-side"><p class="eyebrow">il mio tabellone · ${gameState.size}×${gameState.size}</p>${renderNavalGrid(gameState.ownBoard, { ships: gameState.ships, shipTypes: gameState.shipTypes })}<div class="naval-legend"><span><i class="legend-ship"></i>La mia nave</span><span><i class="legend-hit"></i>Nave colpita</span><span><i class="legend-sunk"></i>Affondata</span></div><p class="muted">Le esplosioni restano sulle caselle colpite; una nave completamente distrutta viene mostrata mezza affondata.</p></div>${bridge}</div></section>`;
}
function renderProfile() { return `<section><p class="eyebrow">profilo giocatore</p><h1>${escapeHtml(state.user.displayName || state.user.username)}</h1><div class="panel" style="max-width:650px"><div class="identity"><div class="avatar" style="width:64px;height:64px;font-size:22px">${initials(state.user.displayName || state.user.username)}</div><div><h2 style="margin:0">${escapeHtml(state.user.displayName || state.user.username)}</h2><p class="muted">@${escapeHtml(state.user.username)} · membro dal ${formatDate(state.user.createdAt)}</p></div></div><div class="section"><p class="muted">${escapeHtml(state.user.bio || 'Aggiungi una bio quando il profilo sarà personalizzabile.')}</p></div><div class="grid"><div><p class="eyebrow">amici</p><h2>${state.friends.length}</h2></div><div><p class="eyebrow">giochi</p><h2>${state.games.length}</h2></div></div></div></section>`; }
function collectGameSettings(form, gameId) { if (gameId === 'battaglia-navale') return { mode: form.get('mode'), boardSize: Number(form.get('boardSize')) || 10, fleetSet: form.get('fleetSet'), abilitiesEnabled: form.get('abilitiesEnabled') === 'on', specialShotsEnabled: form.get('specialShotsEnabled') === 'on' }; if (gameId === 'uno') return { mode: form.get('unoMode') || 'classic' }; if (gameId === 'wordle-coop') return { wordCount: Number(form.get('wordCount')) || 1 }; if (gameId === 'wordle-competitivo') return { wordCount: Number(form.get('wordCount')) || 1, matchMode: form.get('matchMode'), durationSeconds: Number(form.get('durationSeconds')) || 120 }; return {}; }

function bindEvents() {
  document.querySelectorAll('[data-auth]').forEach(button => button.onclick = () => { state.authMode = button.dataset.auth; render(); });
  document.querySelectorAll('[data-view]').forEach(button => button.onclick = () => navigate(button.dataset.view));
  document.querySelectorAll('[data-open-lobby]').forEach(button => button.onclick = () => { state.createLobbyGameId = button.dataset.openLobby || state.games[0]?.id || ''; state.battleLobbyMode = 'classic'; state.createLobbyOpen = true; render(); });
  document.querySelector('[data-close-modal]')?.addEventListener('click', () => { state.createLobbyOpen = false; render(); });
  document.querySelector('#create-game-select')?.addEventListener('change', event => { state.createLobbyGameId = event.target.value; state.battleLobbyMode = 'classic'; render(); });
  document.querySelector('#create-battle-mode')?.addEventListener('change', event => { state.battleLobbyMode = event.target.value; render(); });
  document.querySelectorAll('[data-select-lobby]').forEach(card => card.onclick = event => { if (event.target.closest('button')) return; state.selectedLobbyId = card.dataset.selectLobby; render(); });
  const authForm = document.querySelector('#auth-form'); if (authForm) authForm.onsubmit = async event => { event.preventDefault(); const form = new FormData(authForm); try { const register = state.authMode === 'register'; const result = await api(register ? '/api/auth/register' : '/api/auth/login', { method: 'POST', body: JSON.stringify(register ? { username: form.get('identity'), email: form.get('email'), password: form.get('password'), displayName: form.get('displayName') } : { identity: form.get('identity'), password: form.get('password') }) }); state.user = result.user; await loadData(); } catch (error) { document.querySelector('#form-error').textContent = error.message; } };
  const friendForm = document.querySelector('#friend-form'); if (friendForm) friendForm.onsubmit = async event => { event.preventDefault(); try { await api('/api/friends/request', { method: 'POST', body: JSON.stringify({ username: new FormData(friendForm).get('username') }) }); toast('Richiesta inviata'); friendForm.reset(); } catch (error) { toast(error.message); } };
  document.querySelectorAll('[data-accept]').forEach(button => button.onclick = async () => { try { await api(`/api/friends/requests/${button.dataset.accept}/accept`, { method: 'POST' }); await loadData(); } catch (error) { toast(error.message); } });
  const lobbySettingsForm = document.querySelector('#lobby-settings-form'); if (lobbySettingsForm) lobbySettingsForm.onsubmit = async event => { event.preventDefault(); const form = new FormData(lobbySettingsForm); try { await api(`/api/lobbies/${state.selectedLobbyId}`, { method: 'PATCH', body: JSON.stringify({ gameId: form.get('gameId'), maxPlayers: Number(form.get('maxPlayers')), privacy: form.get('privacy'), settings: collectGameSettings(form, form.get('gameId')) }) }); await loadData(); toast('Impostazioni lobby salvate.'); } catch (error) { toast(error.message); } };
  document.querySelector('#lobby-battle-mode')?.addEventListener('change', event => { state.battleLobbyEditId = state.selectedLobbyId; state.battleLobbyEditMode = event.target.value; render(); });
  const createForm = document.querySelector('#create-lobby-form'); if (createForm) createForm.onsubmit = async event => { event.preventDefault(); const form = new FormData(createForm); try { await api('/api/lobbies', { method: 'POST', body: JSON.stringify({ gameId: form.get('gameId'), maxPlayers: Number(form.get('maxPlayers')), privacy: form.get('privacy'), settings: collectGameSettings(form, form.get('gameId')) }) }); state.createLobbyOpen = false; state.view = 'lobbies'; await loadData(); toast('Lobby creata. Attendi gli altri giocatori, poi avviala.'); } catch (error) { document.querySelector('#lobby-form-error').textContent = error.message; } };
  document.querySelectorAll('[data-join-lobby]').forEach(button => button.onclick = async () => { try { await api(`/api/lobbies/${button.dataset.joinLobby}/join`, { method: 'POST' }); await loadData(); toast('Sei entrato nella lobby. L’host avvierà la partita.'); } catch (error) { toast(error.message); } });
  document.querySelectorAll('[data-invite-friend]').forEach(button => button.onclick = async () => { try { await api(`/api/lobbies/${button.dataset.lobbyId}/invite`, { method: 'POST', body: JSON.stringify({ userId: button.dataset.userId }) }); toast('Invito inviato.'); await loadData(); } catch (error) { toast(error.message); } });
  document.querySelectorAll('[data-start-lobby]').forEach(button => button.onclick = async () => { try { const result = await api(`/api/lobbies/${button.dataset.startLobby}/start`, { method: 'POST' }); state.match = result.match; sessionStorage.setItem('browser-games-active-match', result.match.id); state.view = 'match'; render(); } catch (error) { toast(error.message); } });
  document.querySelector('[data-leave-match]')?.addEventListener('click', () => { if (state.match?.status === 'IN_GAME' && !confirm('Abbandonare la partita? Potresti non poter rientrare.')) return; state.match = null; sessionStorage.removeItem('browser-games-active-match'); state.view = 'lobbies'; render(); });
  document.querySelector('[data-logout]')?.addEventListener('click', async () => { await api('/api/auth/logout', { method: 'POST' }); state.user = null; state.match = null; sessionStorage.removeItem('browser-games-active-match'); state.events?.close(); render(); });
  document.querySelectorAll('[data-tris-cell]').forEach(cell => cell.onclick = async () => { try { const result = await api(`/api/matches/${state.match.id}/action`, { method: 'POST', body: JSON.stringify({ type: 'place_mark', payload: { index: Number(cell.dataset.trisCell) } }) }); state.match = result.match; render(); } catch (error) { toast(error.message); } });
  document.querySelectorAll('[data-uno-card]').forEach(card => card.onclick = async () => { const selected = state.match.state.hand.find(item => item.id === card.dataset.unoCard); const color = selected && ['wild', 'wild4'].includes(selected.value) ? prompt('Scegli colore: red, yellow, green o blue', 'red')?.trim().toLowerCase() : undefined; try { const result = await api(`/api/matches/${state.match.id}/action`, { method: 'POST', body: JSON.stringify({ type: 'play_card', payload: { cardId: card.dataset.unoCard, color } }) }); state.match = result.match; render(); } catch (error) { toast(error.message); } });
  document.querySelector('[data-uno-draw]')?.addEventListener('click', async () => { try { const result = await api(`/api/matches/${state.match.id}/action`, { method: 'POST', body: JSON.stringify({ type: 'draw_card', payload: {} }) }); state.match = result.match; render(); } catch (error) { toast(error.message); } });
  document.querySelector('[data-uno-call]')?.addEventListener('click', async () => { try { const result = await api(`/api/matches/${state.match.id}/action`, { method: 'POST', body: JSON.stringify({ type: 'call_uno', payload: {} }) }); state.match = result.match; render(); } catch (error) { toast(error.message); } });
  document.querySelectorAll('[data-bingo-number]').forEach(cell => cell.onclick = async () => { try { const result = await api(`/api/matches/${state.match.id}/action`, { method: 'POST', body: JSON.stringify({ type: 'call_number', payload: { number: Number(cell.dataset.bingoNumber) } }) }); state.match = result.match; render(); } catch (error) { toast(error.message); } });
  const wordleForm = document.querySelector('#wordle-form'); if (wordleForm) wordleForm.onsubmit = async event => { event.preventDefault(); const form = new FormData(wordleForm); try { const result = await api(`/api/matches/${state.match.id}/action`, { method: 'POST', body: JSON.stringify({ type: 'submit_guess', payload: { guess: form.get('guess') } }) }); state.match = result.match; render(); } catch (error) { toast(error.message); } };
  document.querySelectorAll('[data-ship-select="deck"]').forEach(card => card.onclick = async () => { try { const result = await api(`/api/matches/${state.match.id}/action`, { method: 'POST', body: JSON.stringify({ type: 'add_to_deck', payload: { typeId: card.dataset.selectShipType } }) }); state.match = result.match; render(); } catch (error) { toast(error.message); } });
  document.querySelectorAll('[data-ship-select="placement"]').forEach(card => card.onclick = () => { state.navalSelectedShipId = card.dataset.selectDeckShip || card.dataset.selectShipId; render(); });
  document.querySelectorAll('[data-ship-select="shot"]').forEach(card => card.onclick = () => { state.navalSelectedShipId = card.dataset.selectShipId; state.navalSelectedMode = 'normal'; render(); });
  document.querySelectorAll('[data-shot-mode]').forEach(button => button.onclick = () => { state.navalSelectedMode = button.dataset.shotMode; render(); });
  if (state.view === 'match' && state.match?.gameId === 'battaglia-navale') document.onkeydown = event => { if (state.view !== 'match' || state.match?.gameId !== 'battaglia-navale' || !['r', 't'].includes(event.key.toLowerCase())) return; event.preventDefault(); if (event.key.toLowerCase() === 'r') state.navalOrientation = state.navalOrientation === 'H' ? 'V' : 'H'; if (event.key.toLowerCase() === 't') state.navalMirror = !state.navalMirror; render(); };
  let draggedShip = null;
  document.querySelectorAll('[data-drag-ship]').forEach(card => card.addEventListener('dragstart', event => { draggedShip = { typeId: card.dataset.shipType, deckShipId: card.dataset.deckShipId || undefined, shipId: card.dataset.shipId || undefined }; event.dataTransfer.effectAllowed = 'copy'; event.dataTransfer.setData('text/plain', card.dataset.shipType); card.classList.add('dragging'); }));
  document.querySelectorAll('[data-drag-ship]').forEach(card => card.addEventListener('dragend', () => { card.classList.remove('dragging'); clearShipPreview(document.querySelector('#own-naval-board')); draggedShip = null; }));
  const deckDropzone = document.querySelector('#deck-dropzone'); if (deckDropzone) { deckDropzone.addEventListener('dragover', event => event.preventDefault()); deckDropzone.addEventListener('drop', async event => { event.preventDefault(); if (!draggedShip) return; try { const result = await api(`/api/matches/${state.match.id}/action`, { method: 'POST', body: JSON.stringify({ type: 'add_to_deck', payload: { typeId: draggedShip.typeId } }) }); state.match = result.match; render(); } catch (error) { toast(error.message); } }); }
  document.querySelectorAll('[data-remove-deck]').forEach(button => button.onclick = async () => { try { const result = await api(`/api/matches/${state.match.id}/action`, { method: 'POST', body: JSON.stringify({ type: 'remove_deck_ship', payload: { shipId: button.dataset.removeDeck } }) }); state.match = result.match; render(); } catch (error) { toast(error.message); } });
  document.querySelector('[data-ready-deck]')?.addEventListener('click', async () => { try { const result = await api(`/api/matches/${state.match.id}/action`, { method: 'POST', body: JSON.stringify({ type: 'ready_deck', payload: {} }) }); state.match = result.match; render(); } catch (error) { toast(error.message); } });
  const ownNavalBoard = document.querySelector('#own-naval-board'); if (ownNavalBoard) {
    ownNavalBoard.addEventListener('pointermove', event => { const cell = event.target.closest('[data-naval-row]'); if (!cell || !state.match?.state || state.match.state.phase !== 'SETUP') return; const selected = draggedShip || (() => { const ship = state.match.state.ships.find(item => item.id === state.navalSelectedShipId); if (ship) return { typeId: ship.typeId, deckShipId: state.match.state.mode === 'plus' ? ship.id : undefined, shipId: state.match.state.mode === 'classic' ? ship.id : undefined }; const deckShip = (state.match.state.deck || []).find(item => item.id === state.navalSelectedShipId); return deckShip ? { typeId: deckShip.typeId, deckShipId: deckShip.id } : null; })(); if (!selected) return; showShipPreview(ownNavalBoard, state.match.state, selected, Number(cell.dataset.navalRow), Number(cell.dataset.navalCol), state.navalOrientation, state.navalMirror); });
    ownNavalBoard.addEventListener('dragover', event => { event.preventDefault(); });
    ownNavalBoard.addEventListener('dragleave', event => { if (!ownNavalBoard.contains(event.relatedTarget)) clearShipPreview(ownNavalBoard); });
    ownNavalBoard.addEventListener('click', async event => { if (state.match?.state.phase !== 'SETUP') return; const cell = event.target.closest('[data-naval-row]'); if (!cell) return; const selected = draggedShip || (() => { const deckShip = (state.match.state.deck || []).find(item => item.id === state.navalSelectedShipId); if (deckShip) return { typeId: deckShip.typeId, deckShipId: deckShip.id }; const fleetShip = (state.match.state.fleet || []).find(item => item.id === state.navalSelectedShipId); return fleetShip ? { typeId: fleetShip.typeId, shipId: fleetShip.id } : null; })(); if (!selected) { toast('Seleziona prima una card-nave.'); return; } clearShipPreview(ownNavalBoard); try { const result = await api(`/api/matches/${state.match.id}/action`, { method: 'POST', body: JSON.stringify({ type: 'place_ship', payload: { typeId: selected.typeId, deckShipId: selected.deckShipId, shipId: selected.shipId, row: Number(cell.dataset.navalRow), col: Number(cell.dataset.navalCol), orientation: state.navalOrientation, mirror: state.navalMirror } }) }); state.match = result.match; state.navalSelectedShipId = ''; render(); } catch (error) { toast(error.message); } });
    ownNavalBoard.addEventListener('drop', async event => { event.preventDefault(); const cell = event.target.closest('[data-naval-row]'); clearShipPreview(ownNavalBoard); if (!cell || !draggedShip) return; try { const result = await api(`/api/matches/${state.match.id}/action`, { method: 'POST', body: JSON.stringify({ type: 'place_ship', payload: { typeId: draggedShip.typeId, deckShipId: draggedShip.deckShipId, shipId: draggedShip.shipId, row: Number(cell.dataset.navalRow), col: Number(cell.dataset.navalCol), orientation: state.navalOrientation, mirror: state.navalMirror } }) }); state.match = result.match; state.navalSelectedShipId = ''; render(); } catch (error) { toast(error.message); } finally { draggedShip = null; } });
  }
  document.querySelectorAll('[data-remove-ship]').forEach(button => button.onclick = async () => { try { const result = await api(`/api/matches/${state.match.id}/action`, { method: 'POST', body: JSON.stringify({ type: 'remove_ship', payload: { shipId: button.dataset.removeShip } }) }); state.match = result.match; render(); } catch (error) { toast(error.message); } });
  document.querySelector('[data-ready-fleet]')?.addEventListener('click', async () => { try { const result = await api(`/api/matches/${state.match.id}/action`, { method: 'POST', body: JSON.stringify({ type: 'ready', payload: {} }) }); state.match = result.match; render(); } catch (error) { toast(error.message); } });
  const opponentNavalBoard = document.querySelector('#opponent-naval-board'); if (opponentNavalBoard) { opponentNavalBoard.addEventListener('pointermove', event => { if (state.match?.state.phase !== 'PLAY' || state.match.state.turn !== state.user.id) return; const cell = event.target.closest('[data-naval-row]'); const ship = state.match.state.ships.find(item => item.id === state.navalSelectedShipId); if (!cell || !ship) return; showShotPreview(opponentNavalBoard, state.match.state, ship, state.navalSelectedMode, Number(cell.dataset.navalRow), Number(cell.dataset.navalCol), state.navalOrientation, state.navalMirror); }); opponentNavalBoard.addEventListener('mouseleave', () => clearShipPreview(opponentNavalBoard)); }
  document.querySelectorAll('#opponent-naval-board [data-naval-row]').forEach(cell => cell.onclick = async () => { if (state.match.gameId !== 'battaglia-navale' || state.match.state.phase !== 'PLAY' || state.match.state.turn !== state.user.id) return; const shipId = state.navalSelectedShipId; const mode = state.match.state.mode === 'plus' ? state.navalSelectedMode : 'normal'; if (!shipId) { toast('Scegli una card-nave prima di sparare.'); return; } try { const result = await api(`/api/matches/${state.match.id}/action`, { method: 'POST', body: JSON.stringify({ type: 'fire', payload: { row: Number(cell.dataset.navalRow), col: Number(cell.dataset.navalCol), shipId, mode, orientation: state.navalOrientation, mirror: state.navalMirror } }) }); state.match = result.match; render(); } catch (error) { toast(error.message); } });
  if (state.match?.gameId === 'battaglia-navale' && state.match.state?.lastAction) { const results = state.match.state.lastAction.results || []; const resultKeys = new Set(results.map(item => `${item.row}:${item.col}`)); const hitKeys = new Set(results.filter(item => item.result === 'hit').map(item => `${item.row}:${item.col}`)); const revealKeys = new Set((state.match.state.lastAction.reveals || []).map(item => `${item.row}:${item.col}`)); document.querySelectorAll('[data-naval-row]').forEach(cell => { const key = `${cell.dataset.navalRow}:${cell.dataset.navalCol}`; if (resultKeys.has(key)) cell.classList.add('shot-arrival'); if (hitKeys.has(key)) cell.classList.add('explosion'); if (revealKeys.has(key)) cell.classList.add('reveal-arrival'); }); }
  const boardRoot = document.querySelector('#board-root'); if (boardRoot && state.match?.state) { const board = document.createElement('div'); board.className = 'connect-board'; const myPlayer = state.match.state.players?.find(player => player.id === state.user.id); const canPreview = state.match.state.turn === state.user.id && !state.match.state.winner && !state.match.state.draw; state.match.state.board.forEach((row, r) => row.forEach((value, c) => { const cell = document.createElement('button'); cell.className = `connect-cell ${value || ''}`; cell.dataset.column = c; cell.setAttribute('aria-label', `Riga ${r + 1}, colonna ${c + 1}`); cell.onmouseenter = () => { if (!canPreview || value) return; board.querySelectorAll(`[data-column="${c}"]`).forEach(target => { if (!target.classList.contains('red') && !target.classList.contains('yellow')) target.classList.add(`preview-${myPlayer?.color || 'red'}`); }); }; cell.onmouseleave = () => board.querySelectorAll(`[data-column="${c}"]`).forEach(target => target.classList.remove('preview-red', 'preview-yellow')); cell.onclick = async () => { if (!canPreview) return; try { const result = await api(`/api/matches/${state.match.id}/action`, { method: 'POST', body: JSON.stringify({ type: 'drop_disc', payload: { column: c } }) }); state.match = result.match; render(); } catch (error) { toast(error.message); } }; board.appendChild(cell); })); boardRoot.appendChild(board); }
}

loadData().catch(error => { app.innerHTML = `<main class="auth-screen"><section class="auth-card"><h1>Impossibile avviare l’hub</h1><p class="error">${escapeHtml(error.message)}</p><p class="muted">Avvia il server con <code>npm start</code>.</p></section></main>`; });
