(() => {
  const colors = [['red','Rosso'],['yellow','Giallo'],['green','Verde'],['blue','Blu']];
  let me = null, match = null, busy = false;
  const api = async (path, options = {}) => { const response = await fetch(path, { headers: { 'Content-Type':'application/json', ...(options.headers || {}) }, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Operazione non riuscita.'); return data; };
  const escapeHtml = value => String(value ?? '').replace(/[&<>\"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  function css(){ if(document.getElementById('game-fixes-style'))return; const style=document.createElement('style');style.id='game-fixes-style';style.textContent=`
    .game-turn-banner{position:sticky;top:8px;z-index:100;display:flex;align-items:center;justify-content:center;gap:10px;margin:0 auto 14px;padding:12px 18px;border-radius:14px;font-weight:900;box-shadow:0 8px 30px rgba(0,0,0,.18)}.game-turn-banner.mine{background:#214d31;border:2px solid #53d879;color:#dfffe8}.game-turn-banner.enemy{background:#252936;border:1px solid #4d5363;color:#cbd0da}.game-turn-banner.win{background:#594514;border:2px solid #f2c94c;color:#fff1bd}.game-turn-banner.loss{background:#54252a;border:2px solid #ef6b73;color:#ffe0e2}
    .gf-color-overlay{position:fixed;inset:0;background:rgba(5,7,12,.78);backdrop-filter:blur(7px);display:grid;place-items:center;z-index:9999}.gf-color-card{width:min(430px,90vw);padding:26px;border-radius:22px;background:#171a23;border:1px solid #3a4050;box-shadow:0 30px 80px rgba(0,0,0,.5);text-align:center}.gf-color-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:20px}.gf-color-btn{height:70px;border:0;border-radius:14px;font-size:18px;font-weight:900;cursor:pointer;color:white;text-shadow:0 1px 2px #000}.gf-red{background:#d94b55}.gf-yellow{background:#d5a72e}.gf-green{background:#3ca866}.gf-blue{background:#467bd5}
    .gf-opponents{display:flex;flex-wrap:wrap;justify-content:center;align-items:center;gap:16px;margin:8px auto 22px}.gf-opponent{display:flex;flex-direction:column;align-items:center;gap:6px;min-width:90px}.gf-opponent-name{font-weight:800}.gf-card-back{width:54px;height:74px;border-radius:10px;background:repeating-linear-gradient(45deg,#272d3b 0,#272d3b 5px,#343b4d 5px,#343b4d 10px);border:2px solid #657087;position:relative}.gf-card-back:after{content:'UNO';position:absolute;inset:18px 7px;border-radius:50%;display:grid;place-items:center;background:#c92f3b;color:white;font-weight:1000;font-size:11px;transform:rotate(-18deg)}
    .gf-bingo-owned{outline:3px solid var(--gf-owner-color);box-shadow:0 0 0 2px rgba(255,255,255,.18) inset}.gf-delete-lobby{margin-left:8px}
  `;document.head.appendChild(style); }
  async function loadMatch(){const id=sessionStorage.getItem('browser-games-active-match');if(!id){match=null;return;}try{match=(await api('/api/matches/'+id)).match;}catch{match=null;}}
  function showColorPicker(cardId){if(document.querySelector('.gf-color-overlay'))return;const overlay=document.createElement('div');overlay.className='gf-color-overlay';overlay.innerHTML=`<div class="gf-color-card"><p class="eyebrow">UNO</p><h2>Scegli il colore</h2><div class="gf-color-grid">${colors.map(([id,name])=>`<button class="gf-color-btn gf-${id}" data-gf-color="${id}">${name}</button>`).join('')}</div></div>`;document.body.appendChild(overlay);overlay.querySelectorAll('[data-gf-color]').forEach(button=>button.addEventListener('click',async()=>{if(busy)return;busy=true;try{const result=await api('/api/matches/'+match.id+'/action',{method:'POST',body:JSON.stringify({type:'play_card',payload:{cardId,color:button.dataset.gfColor}})});match=result.match;overlay.remove();location.reload();}catch(error){busy=false;alert(error.message);}}));}
  function interceptUno(){if(!match||match.gameId!=='uno'||match.status==='FINISHED')return;document.querySelectorAll('[data-uno-card]').forEach(button=>{if(button.dataset.gfBound)return;button.dataset.gfBound='1';button.addEventListener('click',event=>{const card=match.state?.hand?.find(item=>item.id===button.dataset.unoCard);if(!card||!['wild','wild4'].includes(card.value))return;event.preventDefault();event.stopImmediatePropagation();if(match.state.turn!==me)return;showColorPicker(card.id);},true);});}
  function renderUnoOpponents(){if(!match||match.gameId!=='uno')return;const table=document.querySelector('.uno-table');if(!table||table.classList.contains('gf-circular-table'))return;let wrap=table.querySelector('.gf-opponents');if(!wrap){wrap=document.createElement('div');wrap.className='gf-opponents';table.prepend(wrap);}const html=(match.state.players||[]).filter(p=>p.id!==me).map(p=>`<div class="gf-opponent"><div class="gf-opponent-name">${escapeHtml(p.displayName||p.username||p.id)}</div><div class="gf-card-back"></div><span class="pill">${p.cardCount} carte</span></div>`).join('');if(wrap.dataset.rendered!==html){wrap.innerHTML=html;wrap.dataset.rendered=html;}}
  function playerName(id){const profile=match?.playerProfiles?.find(p=>p.id===id);return profile?.displayName||profile?.username||id;}
  function turnFeedback(){if(!match||!document.querySelector('.main'))return;const s=match.state||{};let text='',cls='';if(s.winner){text=s.winner===me?'🏆 Hai vinto!':`🏆 ${playerName(s.winner)} ha vinto`;cls=s.winner===me?'win':'loss';}else if(s.draw){text='🤝 Pareggio';cls='win';}else if(s.turn){const mine=s.turn===me;text=mine?'⚡ È il tuo turno':`⏳ È il turno di ${playerName(s.turn)}`;cls=mine?'mine':'enemy';}if(!text)return;let banner=document.querySelector('.game-turn-banner');if(!banner){banner=document.createElement('div');banner.className='game-turn-banner';document.querySelector('.main')?.prepend(banner);}const next=`game-turn-banner ${cls}|${text}`;if(banner.dataset.rendered===next)return;banner.className=`game-turn-banner ${cls}`;banner.textContent=text;banner.dataset.rendered=next;}
  function bingoOwnership(){if(!match||match.gameId!=='bingo')return;const players=match.state?.players||[];const owners=new Map();players.forEach((p,i)=>(p.marked||[]).forEach(n=>{if(!owners.has(n))owners.set(n,[]);owners.get(n).push(i);}));const palette=['#5b8def','#e56b6f','#50b879','#d7a72f','#a66be0','#e98b4b','#42b9b9','#d45ba4'];document.querySelectorAll('[data-bingo-number]').forEach(cell=>{const ids=owners.get(Number(cell.dataset.bingoNumber))||[];const color=ids.length?palette[ids[0]%palette.length]:'';const key=ids.join(',')+'|'+color;if(cell.dataset.gfRendered===key)return;cell.dataset.gfRendered=key;cell.classList.toggle('gf-bingo-owned',!!ids.length);if(ids.length)cell.style.setProperty('--gf-owner-color',color);else cell.style.removeProperty('--gf-owner-color');cell.title=ids.map(i=>playerName(players[i].id)).join(', ');});}
  async function lobbyControls(){if(location.pathname==='/match')return;try{const data=await api('/api/lobbies');document.querySelectorAll('[data-select-lobby]').forEach(card=>{const id=card.dataset.selectLobby,lobby=data.lobbies.find(x=>x.id===id);if(!lobby||!lobby.isHost||card.querySelector('.gf-delete-lobby'))return;const button=document.createElement('button');button.className='btn danger small gf-delete-lobby';button.textContent='Elimina';button.addEventListener('click',async e=>{e.stopPropagation();if(!confirm('Eliminare questa lobby?'))return;try{await api('/api/lobbies/'+id,{method:'DELETE'});location.reload();}catch(err){alert(err.message);}});card.querySelector('.row')?.appendChild(button);});}catch{}}
  async function tick(){css();const id=sessionStorage.getItem('browser-games-active-match');if(id)await loadMatch();else match=null;if(match){turnFeedback();interceptUno();renderUnoOpponents();bingoOwnership();}lobbyControls();}
  api('/api/me').then(r=>{me=r.user?.id||null;tick();});setInterval(tick,900);
})();
