(() => {
  const STYLE_ID = 'profile-avatar-fixes-style';
  const state = { saving: false };
  const api = async (path, options = {}) => { const response = await fetch(path, { headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Operazione non riuscita.'); return data; };
  function injectStyle() { if (document.getElementById(STYLE_ID)) return; const style = document.createElement('style'); style.id = STYLE_ID; style.textContent = `.avatar-picker-panel{display:grid;gap:14px;margin-top:18px}.avatar-picker{display:grid;grid-template-columns:repeat(auto-fill,minmax(78px,1fr));gap:10px;max-height:380px;overflow:auto;padding:4px}.avatar-option{border:2px solid transparent;border-radius:14px;padding:5px;background:#111722;cursor:pointer}.avatar-option.selected{border-color:#9a79ff;box-shadow:0 0 0 2px rgba(154,121,255,.16)}.avatar-option img{display:block;width:100%;aspect-ratio:1;border-radius:50%;object-fit:cover}.profile-current-avatar{width:72px;height:72px;border-radius:50%;object-fit:cover;border:3px solid #9a79ff;background:#111722}`; document.head.appendChild(style); }
  async function loadManifest() { try { const response = await fetch('/profile-mascots/manifest.json', { cache: 'no-store' }); return response.ok ? await response.json() : []; } catch { return []; } }
  async function ensureAvatar() { const me = await api('/api/me'); if (!me.user) return null; if (me.user.avatarId) return me.user.avatarId; const manifest = await loadManifest(); if (!manifest.length) return null; const pick = manifest[Math.floor(Math.random() * manifest.length)].id; const result = await api('/api/profile', { method: 'PATCH', body: JSON.stringify({ avatarId: pick }) }); return result.user?.avatarId || pick; }
  async function renderPicker() {
    const active = document.querySelector('[data-view="profile"].active') || /profilo/i.test(document.querySelector('.topbar .eyebrow')?.textContent || '');
    if (!active) return;
    const root = document.querySelector('.main section'); if (!root || root.querySelector('.avatar-picker-panel')) return;
    const manifest = await loadManifest(); if (!manifest.length) return; const me = await api('/api/me').catch(() => ({ user: null })); if (!me.user) return; const current = await ensureAvatar();
    const panel = document.createElement('div'); panel.className = 'panel avatar-picker-panel';
    panel.innerHTML = `<div class="identity"><img class="profile-current-avatar" src="/profile-mascots/${current}.png" alt=""><div><p class="eyebrow">avatar</p><h2 style="margin:0">Scegli la tua mascotte</h2><p class="muted">Una mascotte viene assegnata casualmente alla creazione. Puoi cambiarla quando vuoi.</p></div></div><div class="avatar-picker">${manifest.map(item => `<button type="button" class="avatar-option ${item.id === current ? 'selected' : ''}" data-avatar-id="${item.id}"><img src="/profile-mascots/${item.id}.png" alt=""></button>`).join('')}</div>`;
    root.appendChild(panel);
    panel.querySelectorAll('[data-avatar-id]').forEach(button => button.onclick = async () => { if (state.saving) return; state.saving = true; try { const result = await api('/api/profile', { method: 'PATCH', body: JSON.stringify({ avatarId: button.dataset.avatarId }) }); panel.querySelectorAll('.avatar-option').forEach(item => item.classList.toggle('selected', item === button)); const preview = panel.querySelector('.profile-current-avatar'); if (preview) preview.src = `/profile-mascots/${result.user.avatarId}.png`; } catch (error) { alert(error.message); } finally { state.saving = false; } });
  }
  injectStyle(); ensureAvatar().catch(() => {}); setInterval(() => renderPicker().catch(() => {}), 700);
})();
