const SIZE = 5;
const LINES = [...Array.from({ length: SIZE }, (_, row) => Array.from({ length: SIZE }, (_, col) => row * SIZE + col)), ...Array.from({ length: SIZE }, (_, col) => Array.from({ length: SIZE }, (_, row) => row * SIZE + col)), ...[[0, 6, 12, 18, 24], [4, 8, 12, 16, 20]]];
function shuffle(items) { const result = items.slice(); for (let i = result.length - 1; i > 0; i -= 1) { const j = Math.floor(Math.random() * (i + 1)); [result[i], result[j]] = [result[j], result[i]]; } return result; }
function createInitialState(players = []) { return { size: SIZE, players: players.map(player => ({ id: player.id, board: shuffle(Array.from({ length: 25 }, (_, index) => index + 1)), marked: [], completedLines: [], bingo: '' })), calledNumbers: [], turn: players[0]?.id || null, winner: null, lastCall: null }; }
function lineList(player) { return LINES.flat().length === 25 ? LINES : LINES; }
function completedLineIds(player) { return lineList(player).map((line, index) => line.every(cell => player.marked.includes(player.board[cell])) ? index : -1).filter(index => index >= 0); }
function nextPlayer(state, id) { const index = state.players.findIndex(player => player.id === id); return state.players[(index + 1) % state.players.length]; }
function validateAction(state, action) { if (state.winner) return { ok: false, error: 'La partita è terminata.' }; if (action.type !== 'call_number') return { ok: false, error: 'Azione sconosciuta.' }; if (action.playerId !== state.turn) return { ok: false, error: 'Non è il tuo turno.' }; const number = Number(action.payload?.number); if (!Number.isInteger(number) || number < 1 || number > 25 || state.calledNumbers.includes(number)) return { ok: false, error: 'Numero non disponibile.' }; return { ok: true, number }; }
function reduce(state, action) { const valid = validateAction(state, action); if (!valid.ok) return { ok: false, error: valid.error, state }; state.calledNumbers.push(valid.number); const newlyCompleted = []; for (const player of state.players) { if (player.board.includes(valid.number)) player.marked.push(valid.number); const lines = completedLineIds(player); const newLines = lines.filter(index => !player.completedLines.includes(index)); player.completedLines = lines; player.bingo = 'BINGO'.slice(0, Math.min(5, player.completedLines.length)); newlyCompleted.push({ playerId: player.id, added: newLines.length, progress: player.bingo }); } const winner = state.players.find(player => player.completedLines.length >= 5); if (winner) state.winner = winner.id; else state.turn = nextPlayer(state, action.playerId).id; state.lastCall = { number: valid.number, playerId: action.playerId, newlyCompleted }; return { ok: true, state, events: [{ type: 'number_called', number: valid.number, playerId: action.playerId, newlyCompleted }] }; }
function getView(state, viewerId) { return { size: state.size, board: state.players.find(player => player.id === viewerId)?.board || [], marked: state.players.find(player => player.id === viewerId)?.marked || [], calledNumbers: state.calledNumbers, turn: state.turn, winner: state.winner, lastCall: state.lastCall, players: state.players.map(player => ({ id: player.id, bingo: player.bingo, progress: player.completedLines.length, markedCount: player.marked.length })) }; }
function result(state) { return state.winner ? { status: 'WON', winnerId: state.winner } : null; }
module.exports = { SIZE, createInitialState, validateAction, reduce, getView, result };
