const COLORS = [
  { id: 'cyan', name: 'Cyan', value: '#5ee7ff' },
  { id: 'lime', name: 'Lime', value: '#79f2a8' },
  { id: 'violet', name: 'Viola', value: '#a78bfa' },
  { id: 'pink', name: 'Rosa', value: '#ff79c6' },
  { id: 'orange', name: 'Arancio', value: '#ff9f5a' },
  { id: 'yellow', name: 'Giallo', value: '#ffd166' },
  { id: 'red', name: 'Rosso', value: '#ff667d' },
  { id: 'blue', name: 'Blu', value: '#6c8cff' }
];
const DIRECTIONS = { up: [0, -1], down: [0, 1], left: [-1, 0], right: [1, 0] };
function normalizeSettings(input = {}) { const size = Math.max(25, Math.min(60, Number(input.boardSize) || 30)); const speedMs = [120, 160, 200, 240].includes(Number(input.speedMs)) ? Number(input.speedMs) : 180; const growthEvery = Math.max(3, Math.min(8, Number(input.growthEvery) || 5)); return { boardSize: size, speedMs, growthEvery }; }
function spawnSnakes(players, size) { const mid = Math.floor(size / 2); return players.map((player, index) => { const y = index === 0 ? mid - 5 : mid + 5; const x = index === 0 ? Math.floor(size * .25) : Math.floor(size * .75); const direction = index === 0 ? 'right' : 'left'; const body = Array.from({ length: 4 }, (_, i) => ({ x: x + (index === 0 ? -i : i), y })); return { id: player.id, color: player.color, direction, nextDirection: direction, body, moves: 0, alive: true, reason: null }; }); }
function initialState(players = [], settings = {}) { const normalized = normalizeSettings(settings); return { phase: 'COLOR_SELECT', size: normalized.boardSize, settings: normalized, colors: COLORS, players: players.map(player => ({ id: player.id, color: null, ready: false, alive: true, score: 4 })), snakes: [], winner: null, loser: null, resultReason: null, startedAt: null, sequence: 0 }; }
function opposite(a, b) { return DIRECTIONS[a][0] + DIRECTIONS[b][0] === 0 && DIRECTIONS[a][1] + DIRECTIONS[b][1] === 0; }
function occupied(body, x, y) { return body.some(cell => cell.x === x && cell.y === y); }
function colorAvailable(state, color, id) { return !state.players.some(player => player.id !== id && player.color === color); }
function beginPlay(state) { return { ...state, phase: 'PLAY', snakes: spawnSnakes(state.players, state.size), startedAt: new Date().toISOString(), sequence: state.sequence + 1 }; }
function chooseColor(state, action) { if (state.phase !== 'COLOR_SELECT') return { ok: false, error: 'La scelta del colore è già terminata.' }; const color = String(action.payload?.color || ''); if (!COLORS.some(item => item.id === color)) return { ok: false, error: 'Colore non valido.' }; if (!colorAvailable(state, color, action.playerId)) return { ok: false, error: 'Questo colore è già stato scelto.' }; const players = state.players.map(player => player.id === action.playerId ? { ...player, color, ready: true } : player); const next = { ...state, players, sequence: state.sequence + 1 }; return { ok: true, state: players.every(player => player.color) ? beginPlay(next) : next, events: [{ type: 'color_chosen', playerId: action.playerId, color }] }; }
function finish(state, loserId, winnerId, reason) { const players = state.players.map(player => player.id === loserId ? { ...player, alive: false } : player); const snakes = state.snakes.map(snake => snake.id === loserId ? { ...snake, alive: false, reason } : snake); return { ok: true, state: { ...state, phase: 'FINISHED', players, snakes, winner: winnerId, loser: loserId, resultReason: reason, sequence: state.sequence + 1 }, events: [{ type: 'snake_finished', loserId, winnerId, reason }] }; }
function move(state, action) { if (state.phase !== 'PLAY') return { ok: false, error: 'La partita non è ancora iniziata.' }; const current = state.snakes.find(snake => snake.id === action.playerId); if (!current || !current.alive) return { ok: false, error: 'Questo serpente non è più in gioco.' }; const requested = String(action.payload?.direction || current.nextDirection); if (!DIRECTIONS[requested]) return { ok: false, error: 'Direzione non valida.' }; if (!opposite(requested, current.direction)) current.nextDirection = requested; const [dx, dy] = DIRECTIONS[current.nextDirection]; const head = current.body[0]; const nextHead = { x: head.x + dx, y: head.y + dy }; const other = state.snakes.find(snake => snake.id !== current.id && snake.alive); if (nextHead.x < 0 || nextHead.y < 0 || nextHead.x >= state.size || nextHead.y >= state.size) return finish(state, current.id, null, 'wall'); if (occupied(current.body, nextHead.x, nextHead.y)) return finish(state, current.id, current.id, 'self'); if (other && occupied(other.body, nextHead.x, nextHead.y)) return finish(state, current.id, other.id, 'head_on_body'); const grows = (current.moves + 1) % state.settings.growthEvery === 0; const body = [nextHead, ...current.body]; if (!grows) body.pop(); if (other && occupied(other.body, body[body.length - 1].x, body[body.length - 1].y)) return finish(state, other.id, current.id, 'tail_touch'); const snakes = state.snakes.map(snake => snake.id === current.id ? { ...snake, body, direction: current.nextDirection, moves: snake.moves + 1 } : snake); const players = state.players.map(player => player.id === current.id ? { ...player, score: body.length } : player); return { ok: true, state: { ...state, snakes, players, sequence: state.sequence + 1 }, events: [{ type: 'snake_moved', playerId: current.id, head: nextHead }] }; }
function reduce(state, action) { if (action.type === 'choose_color') return chooseColor(state, action); if (action.type === 'move') return move(state, action); return { ok: false, error: 'Azione Snake sconosciuta.' }; }
function result(state) { return state.phase === 'FINISHED' ? { status: state.winner ? 'WON' : 'LOST', winnerId: state.winner, loserId: state.loser, reason: state.resultReason } : null; }
function getView(state) { return state; }
module.exports = { COLORS, normalizeSettings, initialState, reduce, result, getView };
