function plusCategory(size) { return size <= 3 ? 'small' : size <= 6 ? 'medium' : 'large'; }
function lineShape(size) { return Array.from({ length: size }, (_, index) => [0, index]); }
function columnShape(size) { return Array.from({ length: size }, (_, index) => [index, 0]); }
function lShape(size) { return [...Array.from({ length: size - 1 }, (_, index) => [index, 0]), [size - 2, 1]]; }
function hookShape(size) { return [...Array.from({ length: size - 1 }, (_, index) => [0, index]), [1, size - 2]]; }
function zigzagShape(size) { return Array.from({ length: size }, (_, index) => [index, Math.floor(index / 2)]); }
const PLUS_POWER_LIBRARY = [
  { kind: 'ability', label: 'Abilità: Sonar a diamante', pattern: 'diamond9' },
  { kind: 'special', label: 'Colpo speciale: Raffica 1×5', pattern: 'line5' },
  { kind: 'ability', label: 'Abilità: Anello perimetrale', pattern: 'ring8' },
  { kind: 'special', label: 'Colpo speciale: Croce lunga', pattern: 'cross9' },
  { kind: 'ability', label: 'Abilità: Occhiata agli angoli', pattern: 'corners4' },
  { kind: 'special', label: 'Colpo speciale: Rosa concentrata', pattern: 'rose9' },
  { kind: 'ability', label: 'Abilità: Radar diagonale', pattern: 'diagonal7' },
  { kind: 'special', label: 'Colpo speciale: Stella a otto punte', pattern: 'star8' },
  { kind: 'ability', label: 'Abilità: Scansione a cavallo', pattern: 'knight8' },
  { kind: 'special', label: 'Colpo speciale: Triade alternata', pattern: 'triad3' },
  { kind: 'ability', label: 'Abilità: Finestra a ventaglio', pattern: 'fan7' },
  { kind: 'special', label: 'Colpo speciale: Impatto a onda', pattern: 'wave7' },
  { kind: 'ability', label: 'Abilità: Halo tattico', pattern: 'halo12' },
  { kind: 'special', label: 'Colpo speciale: Quadrato d’assedio', pattern: 'square9' },
  { kind: 'ability', label: 'Abilità: Traccia verticale', pattern: 'line5' },
  { kind: 'special', label: 'Colpo speciale: Diagonale spezzata', pattern: 'diagonal7' }
];
function plusPower(id, name, variant) {
  const power = PLUS_POWER_LIBRARY[variant % PLUS_POWER_LIBRARY.length]; const powerId = `${id}-${power.kind}`; const label = `${power.label} · ${name}`;
  return power.kind === 'ability' ? { ability: { id: powerId, name: label, kind: 'reveal', pattern: power.pattern } } : { specialShot: { id: powerId, name: label, pattern: power.pattern } };
}
function makePlusShip(size, variant, name, shape) {
  const id = `plus-${size}-${variant + 1}`; return { id, name, size, category: plusCategory(size), class: plusCategory(size), cost: size, shape, ...plusPower(id, name, variant) };
}
function expansionShape(size, seed) { const width = Math.max(4, Math.min(9, Math.ceil(size / 2) + 2)); return Array.from({ length: size }, (_, index) => [index, (index * seed + index % 3) % width]); }
const LEGACY_PLUS_SHIPS = [
  { id: 'scout', name: 'Scout', size: 1, category: 'small', class: 'small', cost: 1, shape: [[0, 0]], ability: { id: 'reveal3x3', name: 'Abilità: Scanner 3×3', kind: 'reveal', pattern: 'square3' } },
  { id: 'patrol', name: 'Pattugliatore', size: 2, category: 'small', class: 'small', cost: 2, shape: [[0, 0], [0, 1]], specialShot: { id: 'line3', name: 'Colpo speciale: Raffica 1×3', pattern: 'line3' } },
  { id: 'corvette', name: 'Corvetta', size: 3, category: 'small', class: 'small', cost: 3, shape: [[0, 0], [1, 0], [2, 0]], specialShot: { id: 'cross5-corvette', name: 'Colpo speciale: Salva a croce · 5 colpi · Corvetta', pattern: 'cross5' } },
  { id: 'gunboat', name: 'Gunboat', size: 3, category: 'medium', class: 'medium', cost: 3, shape: [[0, 0], [1, 0], [1, 1]], ability: { id: 'revealCross-gunboat', name: 'Abilità: Eco a croce · Gunboat', kind: 'reveal', pattern: 'cross5' } },
  { id: 'destroyer', name: 'Cacciatorpediniere', size: 4, category: 'medium', class: 'medium', cost: 4, shape: [[0, 0], [0, 1], [1, 0], [1, 1]], specialShot: { id: 'square4-destroyer', name: 'Colpo speciale: Bombardamento quadrato · 4 colpi · Destroyer', pattern: 'square4' } },
  { id: 'frigate', name: 'Fregata', size: 4, category: 'medium', class: 'medium', cost: 4, shape: [[0, 1], [1, 0], [1, 1], [1, 2]], ability: { id: 'revealLine-frigate', name: 'Abilità: Ricognizione 1×3 · Fregata', kind: 'reveal', pattern: 'line3' } },
  { id: 'submarine', name: 'Sommergibile', size: 5, category: 'medium', class: 'medium', cost: 5, shape: [[0, 0], [0, 1], [1, 1], [1, 2], [2, 2]], specialShot: { id: 'rose5-submarine', name: 'Colpo speciale: Raffica a rosa · Sommergibile', pattern: 'rose5' } },
  { id: 'cruiser', name: 'Incrociatore', size: 5, category: 'medium', class: 'medium', cost: 5, shape: [[0, 0], [1, 0], [2, 0], [2, 1], [2, 2]], ability: { id: 'revealRing-cruiser', name: 'Abilità: Periscopio ad anello · Incrociatore', kind: 'reveal', pattern: 'ring8' } },
  { id: 'battleship', name: 'Corazzata', size: 6, category: 'medium', class: 'medium', cost: 6, shape: [[0, 1], [1, 0], [1, 1], [1, 2], [2, 1], [2, 2]], specialShot: { id: 'diagonal5-battleship', name: 'Colpo speciale: Salva diagonale · Corazzata', pattern: 'diagonal5' } },
  { id: 'carrier', name: 'Portaerei', size: 6, category: 'large', class: 'large', cost: 6, shape: [[0, 0], [0, 1], [0, 2], [1, 2], [1, 3], [1, 4]], ability: { id: 'reveal3x3-carrier', name: 'Abilità: Radar di bordo 3×3 · Portaerei', kind: 'reveal', pattern: 'square3' } },
  { id: 'dreadnought', name: 'Dreadnought', size: 7, category: 'large', class: 'large', cost: 7, shape: [[0, 0], [0, 1], [0, 2], [1, 0], [1, 2], [2, 0], [2, 1]], specialShot: { id: 'cross7-dreadnought', name: 'Colpo speciale: Cannone a croce · 7 colpi · Dreadnought', pattern: 'cross7' } },
  { id: 'fortress', name: 'Fortezza Mobile', size: 9, category: 'large', class: 'large', cost: 9, shape: [[0, 1], [0, 2], [1, 0], [1, 1], [1, 2], [1, 3], [2, 0], [2, 1], [2, 2]], ability: { id: 'reveal3x3-fortress', name: 'Abilità: Centro comando 3×3 · Fortezza', kind: 'reveal', pattern: 'square3' } }
];
const PLUS_SHIP_TYPES = [
  ...LEGACY_PLUS_SHIPS,
  makePlusShip(3, 2, 'Corvetta Saetta', lineShape(3)),
  makePlusShip(3, 3, 'Corvetta Gabbiano', [[0, 1], [1, 0], [1, 1]]),
  makePlusShip(3, 4, 'Corvetta Tridente', [[0, 0], [0, 1], [1, 0]]),
  ...Array.from({ length: 7 }, (_, offset) => {
    const size = offset + 4;
    const shapes = [lineShape(size), columnShape(size), lShape(size), hookShape(size), zigzagShape(size)];
    const names = ['Linea', 'Albero', 'Gancio', 'Prua Alta', 'Serpente'];
    return shapes.map((shape, variant) => makePlusShip(size, variant, `Nave ${names[variant]} ${size}`, shape));
  }).flat()
];
const PLUS_EXPANSION_NAMES = ['Manta Lunare', 'Raggio Polare', 'Vela Fantasma', 'Arco Cremisi', 'Fenice Blu', 'Orca Prisma', 'Serpente Solare', 'Drago d’Acciaio', 'Falco d’Ombra', 'Leviatano', 'Aquila Nebula', 'Balena Stellare', 'Squalo Meccanico', 'Gabbiano d’Argento', 'Kraken Tattico', 'Lince Quantica', 'Tritone Nero', 'Rondine Ionica', 'Medusa Reattiva', 'Colosso Mareale', 'Basilisco', 'Cometa d’Assalto', 'Cigno Radar', 'Armadillo Navale', 'Tigre di Marea', 'Vortice', 'Sentinella Aurora', 'Mantide d’Acciaio', 'Cobra Orbitale', 'Monolite'];
const PLUS_EXPANSION_SIZES = [3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 10];
PLUS_EXPANSION_SIZES.forEach((size, index) => PLUS_SHIP_TYPES.push(makePlusShip(size, 20 + index, PLUS_EXPANSION_NAMES[index], expansionShape(size, index + 8))));

const CLASSIC_SHIP_TYPES = [
  { id: 'classic-carrier', name: 'Portaerei', size: 5, category: 'large', class: 'large', cost: 5, shape: [[0, 0], [0, 1], [0, 2], [0, 3], [0, 4]], availability: 'classic' },
  { id: 'classic-battleship', name: 'Corazzata', size: 4, category: 'medium', class: 'medium', cost: 4, shape: [[0, 0], [0, 1], [0, 2], [0, 3]], availability: 'classic' },
  { id: 'classic-cruiser', name: 'Incrociatore', size: 3, category: 'medium', class: 'medium', cost: 3, shape: [[0, 0], [0, 1], [0, 2]], availability: 'classic' },
  { id: 'classic-submarine', name: 'Sottomarino', size: 3, category: 'medium', class: 'medium', cost: 3, shape: [[0, 0], [0, 1], [0, 2]], availability: 'classic' },
  { id: 'classic-destroyer', name: 'Cacciatorpediniere', size: 2, category: 'small', class: 'small', cost: 2, shape: [[0, 0], [0, 1]], availability: 'classic' },
  { id: 'classic-carrier-4', name: 'Portaerei', size: 4, category: 'large', class: 'large', cost: 4, shape: [[0, 0], [0, 1], [0, 2], [0, 3]], availability: 'classic' },
  { id: 'classic-battleship-3', name: 'Corazzata / Incrociatore', size: 3, category: 'medium', class: 'medium', cost: 3, shape: [[0, 0], [0, 1], [0, 2]], availability: 'classic' },
  { id: 'classic-submarine-2', name: 'Sottomarino', size: 2, category: 'small', class: 'small', cost: 2, shape: [[0, 0], [0, 1]], availability: 'classic' },
  { id: 'classic-assault-1', name: 'Nave d’assalto', size: 1, category: 'small', class: 'small', cost: 1, shape: [[0, 0]], availability: 'classic' },
  { id: 'classic-flagship-t', name: 'Nave Ammiraglia a T', size: 4, category: 'large', class: 'large', cost: 4, shape: [[0, 0], [0, 1], [0, 2], [1, 1]], availability: 'classic' },
  { id: 'classic-heavy-l', name: 'Incrociatore pesante a L', size: 4, category: 'medium', class: 'medium', cost: 4, shape: [[0, 0], [1, 0], [2, 0], [2, 1]], availability: 'classic' },
  { id: 'classic-light-z', name: 'Incrociatore leggero a Z', size: 4, category: 'medium', class: 'medium', cost: 4, shape: [[0, 0], [0, 1], [1, 1], [1, 2]], availability: 'classic' },
  { id: 'classic-square', name: 'Corazzata Quadrata', size: 4, category: 'medium', class: 'medium', cost: 4, shape: [[0, 0], [0, 1], [1, 0], [1, 1]], availability: 'classic' },
  { id: 'classic-mine', name: 'Mina / Boa marina', size: 1, category: 'small', class: 'small', cost: 1, shape: [[0, 0]], availability: 'classic' }
];

const SHIP_TYPES = [...PLUS_SHIP_TYPES, ...CLASSIC_SHIP_TYPES];
const CLASSIC_FLEET_SETS = {
  daituunnome: { id: 'daituunnome', name: 'Daituunnome', boardSize: 10, description: 'Flotta classica standard · 5 navi lineari', ships: [{ typeId: 'classic-carrier', count: 1 }, { typeId: 'classic-battleship', count: 1 }, { typeId: 'classic-cruiser', count: 1 }, { typeId: 'classic-submarine', count: 1 }, { typeId: 'classic-destroyer', count: 1 }] },
  daituunnome2: { id: 'daituunnome2', name: 'Daituunnome 2', boardSize: 10, description: 'Flotta numerosa · 10 navi lineari', ships: [{ typeId: 'classic-carrier-4', count: 1 }, { typeId: 'classic-battleship-3', count: 2 }, { typeId: 'classic-submarine-2', count: 3 }, { typeId: 'classic-assault-1', count: 4 }] },
  daiunnometu3: { id: 'daiunnometu3', name: 'Daiunnometu 3', boardSize: 10, description: 'Flotta geometrica · T, L, Z e quadrata', ships: [{ typeId: 'classic-flagship-t', count: 1 }, { typeId: 'classic-heavy-l', count: 1 }, { typeId: 'classic-light-z', count: 1 }, { typeId: 'classic-square', count: 1 }, { typeId: 'classic-mine', count: 1 }] }
};
const CLASSIC_FLEET = CLASSIC_FLEET_SETS.daituunnome.ships.map(item => item.typeId);
const CLASSIC_BOARD_SIZES = [10];
const PLUS_BOARD_OPTIONS = [{ size: 11, budget: 25 }, { size: 13, budget: 30 }, { size: 15, budget: 35 }, { size: 25, budget: 45 }, { size: 35, budget: 55 }, { size: 50, budget: 80 }];
const PLUS_MIN_SHIPS = 5;
const key = (row, col) => `${row}:${col}`;
function clampSize(size, mode = 'plus', selectedFleetSet = 'daituunnome') { if (mode === 'classic') return CLASSIC_FLEET_SETS[selectedFleetSet]?.boardSize || 10; const value = Number(size); if (value === 10) return 10; return PLUS_BOARD_OPTIONS.reduce((closest, option) => Math.abs(option.size - (value || 11)) < Math.abs(closest.size - (value || 11)) ? option : closest, PLUS_BOARD_OPTIONS[0]).size; }
function deckBudget(size) { if (Number(size) === 10) return 30; return PLUS_BOARD_OPTIONS.find(option => option.size === Number(size))?.budget || 25; }
function shipType(typeId) { return SHIP_TYPES.find(type => type.id === typeId); }
function fleetSet(input) { return CLASSIC_FLEET_SETS[input] ? input : 'daituunnome'; }
function buildClassicFleet(setId) { let number = 0; return CLASSIC_FLEET_SETS[setId].ships.flatMap(spec => Array.from({ length: spec.count }, () => ({ id: `fleet_${setId}_${number += 1}`, typeId: spec.typeId }))); }
function cellsFor(ship) { const type = shipType(ship.typeId); const mirrored = ship.mirror ? type.shape.map(([row, col]) => [row, -col]) : type.shape; const rotated = ship.orientation === 'V' ? mirrored.map(([row, col]) => [col, -row]) : mirrored; const minRow = Math.min(...rotated.map(([row]) => row)); const minCol = Math.min(...rotated.map(([, col]) => col)); return rotated.map(([row, col]) => ({ row: ship.row + row - minRow, col: ship.col + col - minCol })); }
function makeObstacles(size, mode) { if (mode !== 'plus') return []; const count = Math.min(Math.floor(size * size * 0.04), 120); const result = new Set(); while (result.size < count) result.add(key(Math.floor(Math.random() * size), Math.floor(Math.random() * size))); return [...result].map(value => { const [row, col] = value.split(':').map(Number); return { row, col, type: Math.random() > .5 ? 'rock' : 'island' }; }); }
function createInitialState(players = [], settings = {}) { const mode = settings.mode === 'plus' ? 'plus' : 'classic'; const selectedFleetSet = fleetSet(settings.fleetSet); const size = clampSize(settings.boardSize, mode, selectedFleetSet); const obstacles = makeObstacles(size, mode); return { mode, fleetSet: selectedFleetSet, size, deckBudget: deckBudget(size), minDeckShips: PLUS_MIN_SHIPS, abilitiesEnabled: mode === 'plus' ? settings.abilitiesEnabled !== false : false, specialShotsEnabled: mode === 'plus' ? settings.specialShotsEnabled !== false : false, obstacles, phase: mode === 'plus' ? 'DECK_BUILD' : 'SETUP', players: players.map(player => ({ id: player.id, fleet: mode === 'classic' ? buildClassicFleet(selectedFleetSet) : [], deck: [], deckReady: false, ships: [], ready: false, shots: [], reveals: [], receivedShots: [] })), turn: null, winner: null, lastAction: null }; }
function player(state, id) { return state.players.find(item => item.id === id); }
function enemy(state, id) { return state.players.find(item => item.id !== id); }
function statsFor(current) { return current.ships.reduce((stats, ship) => { const type = shipType(ship.typeId); const category = type?.category || 'medium'; stats.cost += type?.cost || 0; stats[category] += 1; return stats; }, { cost: 0, small: 0, medium: 0, large: 0 }); }
function statsForList(list) { return statsFor({ ships: list }); }
function occupiedBy(ships, row, col, exceptId = null) { return ships.some(ship => ship.id !== exceptId && cellsFor(ship).some(cell => cell.row === row && cell.col === col)); }
function hasObstacle(state, row, col) { return state.obstacles.some(obstacle => obstacle.row === row && obstacle.col === col); }
function sameFleet(left, right) { const count = list => list.reduce((map, item) => map.set(item.typeId, (map.get(item.typeId) || 0) + 1), new Map()); const a = count(left); const b = count(right); return a.size === b.size && [...a].every(([typeId, amount]) => b.get(typeId) === amount); }
function placementError(state, current, input) { const type = shipType(input.typeId); if (!type) return 'Tipo di nave non valido.'; const row = Number(input.row); const col = Number(input.col); const orientation = input.orientation === 'V' ? 'V' : 'H'; const mirror = input.mirror === true || input.mirror === 'true'; if (!Number.isInteger(row) || !Number.isInteger(col)) return 'Coordinate non valide.'; const validFleetShip = state.mode === 'classic' && current.fleet.some(item => item.id === input.shipId && item.typeId === type.id); const validDeckShip = state.mode === 'plus' && current.deck.some(item => item.id === input.shipId && item.typeId === type.id); if (state.mode === 'classic' && !validFleetShip) return 'Questa nave non appartiene al set selezionato.'; if (state.mode === 'plus' && !validDeckShip) return 'Questa nave non fa parte del tuo deck.'; const ship = { id: input.shipId, typeId: type.id, row, col, orientation, mirror }; const cells = cellsFor(ship); if (cells.some(cell => cell.row < 0 || cell.col < 0 || cell.row >= state.size || cell.col >= state.size)) return 'La nave esce dalla mappa.'; if (cells.some(cell => hasObstacle(state, cell.row, cell.col))) return 'Una roccia o un’isola blocca il piazzamento.'; if (cells.some(cell => occupiedBy(current.ships, cell.row, cell.col, input.shipId))) return 'Le navi non possono sovrapporsi.'; const ships = [...current.ships.filter(item => item.id !== input.shipId), ship]; const stats = statsFor({ ships }); if (state.mode === 'plus' && stats.cost > state.deckBudget) return `Budget deck superato: ${stats.cost}/${state.deckBudget}.`; if (state.mode === 'plus' && stats.small > 2) return 'Puoi schierare al massimo due navi piccole.'; if (state.mode === 'plus' && stats.large > 1) return 'Puoi schierare al massimo una nave grande.'; return null; }
function readyError(state, current) { if (!current.ships.length) return 'Devi schierare almeno una nave.'; if (state.mode === 'classic') { if (current.ships.length !== current.fleet.length || !sameFleet(current.ships, current.fleet) || current.ships.some(ship => !current.fleet.some(item => item.id === ship.id))) return 'Devi posizionare esattamente il set di navi scelto.'; } else if (current.ships.length < PLUS_MIN_SHIPS) return `Devi posizionare almeno ${PLUS_MIN_SHIPS} navi.`; else if (current.ships.length !== current.deck.length || current.ships.some(ship => !current.deck.some(deckShip => deckShip.id === ship.id))) return 'Devi posizionare tutte le navi che hai scelto nel deck.'; return null; }
function deckError(state, current, typeId) { const type = shipType(typeId); if (!type || type.availability === 'classic') return 'Tipo di nave non valido per la modalità Plus.'; if (current.deck.some(ship => ship.typeId === typeId)) return 'Questa nave è già nel deck.'; const deck = [...current.deck, { id: 'preview', typeId }]; const stats = statsForList(deck); if (stats.cost > state.deckBudget) return `Budget deck superato: ${stats.cost}/${state.deckBudget}.`; if (stats.small > 2) return 'Puoi scegliere al massimo due navi piccole.'; if (stats.large > 1) return 'Puoi scegliere al massimo una nave grande.'; return null; }
function cooldownError(state, current, ship) { if (state.mode !== 'plus' || (!state.abilitiesEnabled && !state.specialShotsEnabled)) return null; if (!ship) return 'Devi scegliere quale nave usare per sparare.'; return (ship.cooldown || []).length >= 3 ? 'Questa nave è in ricarica: usa tre navi differenti prima di riattivarla.' : null; }
function validateAction(state, action) { const current = player(state, action.playerId); if (!current) return { ok: false, error: 'Giocatore non autorizzato.' }; if (state.phase === 'DECK_BUILD') { if (action.type === 'add_to_deck') { const error = deckError(state, current, action.payload?.typeId); return error ? { ok: false, error } : { ok: true }; } if (action.type === 'remove_deck_ship') return current.deck.some(ship => ship.id === action.payload?.shipId) ? { ok: true } : { ok: false, error: 'Nave non trovata nel deck.' }; if (action.type === 'ready_deck') { const stats = statsForList(current.deck); if (current.deck.length < PLUS_MIN_SHIPS || stats.small > 2 || stats.large > 1 || stats.cost > state.deckBudget) return { ok: false, error: `Il deck deve avere almeno ${PLUS_MIN_SHIPS} navi e rispettare budget e categorie.` }; return { ok: true }; } return { ok: false, error: 'Prima di piazzare le navi devi completare il deck.' }; }
  if (state.phase === 'SETUP') { if (action.type === 'place_ship') { const payload = action.payload || {}; const error = placementError(state, current, { ...payload, shipId: state.mode === 'plus' ? payload.deckShipId : payload.shipId }); return error ? { ok: false, error } : { ok: true }; } if (action.type === 'remove_ship') return current.ships.some(ship => ship.id === action.payload?.shipId) ? { ok: true } : { ok: false, error: 'Nave non trovata.' }; if (action.type === 'ready') { const error = readyError(state, current); return error ? { ok: false, error } : { ok: true }; } return { ok: false, error: 'Durante il pregame puoi solo posizionare, rimuovere o confermare le navi.' }; }
  if (state.phase !== 'PLAY' || state.turn !== action.playerId) return { ok: false, error: 'Non è il tuo turno.' }; if (action.type !== 'fire') return { ok: false, error: 'Azione sconosciuta.' }; const payload = action.payload || {}; const row = Number(payload.row); const col = Number(payload.col); if (!Number.isInteger(row) || !Number.isInteger(col) || row < 0 || col < 0 || row >= state.size || col >= state.size) return { ok: false, error: 'Coordinate non valide.' }; if (current.shots.some(shot => shot.row === row && shot.col === col)) return { ok: false, error: 'Hai già attaccato questa casella.' }; const selected = current.ships.find(ship => ship.id === payload.shipId); const cooldown = cooldownError(state, current, selected); if (cooldown) return { ok: false, error: cooldown }; if (state.mode === 'plus' && !selected) return { ok: false, error: 'Scegli una nave prima di sparare.' }; const type = selected && shipType(selected.typeId); if (payload.mode === 'ability' && (!state.abilitiesEnabled || !type?.ability)) return { ok: false, error: 'Questa abilità non è attiva o non appartiene alla nave scelta.' }; if (payload.mode === 'special' && (!state.specialShotsEnabled || !type?.specialShot)) return { ok: false, error: 'Questo colpo speciale non è attivo o non appartiene alla nave scelta.' }; return { ok: true, row, col, selected, type }; }
function patternCells(row, col, pattern, orientation = 'H', mirror = false) { let offsets; if (pattern === 'line3' || pattern === 'line5') { const radius = pattern === 'line5' ? 2 : 1; offsets = Array.from({ length: radius * 2 + 1 }, (_, index) => orientation === 'V' ? [index - radius, 0] : [0, index - radius]); } else if (pattern === 'cross5') offsets = [[0, 0], [-1, 0], [1, 0], [0, -1], [0, 1]]; else if (pattern === 'cross7') offsets = [[0, 0], [-1, 0], [1, 0], [0, -1], [0, 1], [-2, 0], [2, 0]]; else if (pattern === 'cross9') offsets = [[0, 0], [-1, 0], [1, 0], [-2, 0], [2, 0], [-3, 0], [3, 0], [-4, 0], [4, 0]]; else if (pattern === 'square4') offsets = [[0, 0], [0, 1], [1, 0], [1, 1]]; else if (pattern === 'square3' || pattern === 'square9' || pattern === 'rose9') offsets = Array.from({ length: 9 }, (_, index) => [Math.floor(index / 3) - 1, (index % 3) - 1]); else if (pattern === 'rose5') offsets = [[0, 0], [-1, -1], [-1, 1], [1, -1], [1, 1]]; else if (pattern === 'diamond9') offsets = [[0, 0], [-1, 0], [1, 0], [0, -1], [0, 1], [-1, -1], [-1, 1], [1, -1], [1, 1]]; else if (pattern === 'ring8') offsets = [[-1, -1], [-1, 0], [-1, 1], [0, -1], [0, 1], [1, -1], [1, 0], [1, 1]]; else if (pattern === 'corners4') offsets = [[-1, -1], [-1, 1], [1, -1], [1, 1]]; else if (pattern === 'diagonal5') offsets = [[0, 0], [-1, -1], [1, 1], [-1, 1], [1, -1]]; else if (pattern === 'diagonal7') offsets = [[0, 0], [-3, -3], [-2, -2], [-1, -1], [1, 1], [2, 2], [3, 3]]; else if (pattern === 'star8' || pattern === 'knight8') offsets = [[-2, -1], [-2, 1], [-1, -2], [-1, 2], [1, -2], [1, 2], [2, -1], [2, 1]]; else if (pattern === 'triad3') offsets = [[0, 0], [-1, 1], [1, 1]]; else if (pattern === 'fan7') offsets = [[0, 0], [0, 1], [0, 2], [1, 1], [2, 0], [2, 1], [2, 2]]; else if (pattern === 'wave7') offsets = [[0, -3], [1, -2], [-1, -1], [0, 0], [1, 1], [-1, 2], [0, 3]]; else if (pattern === 'halo12') offsets = [[-2, -1], [-2, 0], [-2, 1], [-1, -2], [-1, 2], [0, -2], [0, 2], [1, -2], [1, 2], [2, -1], [2, 0], [2, 1]]; else offsets = [[0, 0]]; const cells = offsets.map(([deltaRow, deltaCol]) => ({ row: row + deltaRow, col: col + (mirror ? -deltaCol : deltaCol) })); return cells; }
function attackPlan(state, selected, payload) { const type = selected && shipType(selected.typeId); if (!selected || !type || state.mode !== 'plus') return { damage: [{ row: payload.row, col: payload.col }], reveal: [] }; if (payload.mode === 'special' && state.specialShotsEnabled) return { damage: patternCells(payload.row, payload.col, type.specialShot.pattern, payload.orientation, payload.mirror), reveal: [] }; if (payload.mode === 'ability' && state.abilitiesEnabled) return { damage: [{ row: payload.row, col: payload.col }], reveal: patternCells(payload.row, payload.col, type.ability.pattern, payload.orientation, payload.mirror).filter(cell => cell.row !== payload.row || cell.col !== payload.col) }; return { damage: [{ row: payload.row, col: payload.col }], reveal: [] }; }
function applyShot(target, shot) { if (target.receivedShots.some(item => item.row === shot.row && item.col === shot.col)) return 'repeat'; target.receivedShots.push(shot); const hitShip = target.ships.find(ship => cellsFor(ship).some(cell => cell.row === shot.row && cell.col === shot.col)); if (!hitShip) return 'miss'; hitShip.hits.push(key(shot.row, shot.col)); return 'hit'; }
function revealContent(state, target, row, col) { const obstacle = state.obstacles.find(item => item.row === row && item.col === col); if (obstacle) return { type: 'obstacle', obstacle: obstacle.type, revealed: true }; const ship = target.ships.find(item => cellsFor(item).some(cell => cell.row === row && cell.col === col)); return ship ? { type: ship.typeId, revealed: true } : { type: 'revealed', revealed: true }; }
function shipIsSunk(target, ship) { return cellsFor(ship).every(cell => ship.hits.includes(key(cell.row, cell.col))); }
function allSunk(target) { return target.ships.length > 0 && target.ships.every(ship => shipIsSunk(target, ship)); }
function updateCooldowns(current, selected) { if (!selected) return; for (const ship of current.ships) { ship.cooldown = ship.cooldown || []; if (ship.id === selected.id) ship.cooldown = []; else if (!ship.cooldown.includes(selected.id)) ship.cooldown.push(selected.id); } }
function reduce(state, action) { const valid = validateAction(state, action); if (!valid.ok) return { ok: false, error: valid.error, state }; const current = player(state, action.playerId); if (state.phase === 'DECK_BUILD') { if (action.type === 'add_to_deck') current.deck.push({ id: `deck_${Date.now()}_${Math.random().toString(16).slice(2)}`, typeId: action.payload.typeId }); else if (action.type === 'remove_deck_ship') current.deck = current.deck.filter(ship => ship.id !== action.payload.shipId); else if (action.type === 'ready_deck') current.deckReady = true; if (state.players.every(item => item.deckReady)) state.phase = 'SETUP'; return { ok: true, state, events: [{ type: action.type, playerId: action.playerId, phase: state.phase }] }; }
  if (state.phase === 'SETUP') { if (action.type === 'place_ship') { const payload = action.payload || {}; const shipId = state.mode === 'plus' ? payload.deckShipId : payload.shipId; const type = shipType(payload.typeId); const placementPayload = { ...payload, shipId }; const error = placementError(state, current, placementPayload); if (error) return { ok: false, error, state }; const ship = { id: shipId, typeId: type.id, row: Number(payload.row), col: Number(payload.col), orientation: payload.orientation === 'V' ? 'V' : 'H', mirror: payload.mirror === true || payload.mirror === 'true', hits: [], cooldown: [] }; current.ships = [...current.ships.filter(item => item.id !== ship.id), ship]; } else if (action.type === 'remove_ship') current.ships = current.ships.filter(ship => ship.id !== action.payload.shipId); else if (action.type === 'ready') current.ready = true; if (state.players.every(item => item.ready)) { state.phase = 'PLAY'; state.turn = state.players[0].id; } return { ok: true, state, events: [{ type: action.type, playerId: action.playerId, phase: state.phase }] }; }
  const target = enemy(state, action.playerId); const plan = attackPlan(state, valid.selected, action.payload || {}); const results = []; const resolved = new Set(); for (const shot of plan.damage) { const shotKey = key(shot.row, shot.col); if (resolved.has(shotKey)) continue; resolved.add(shotKey); if (shot.row < 0 || shot.col < 0 || shot.row >= state.size || shot.col >= state.size) continue; if (hasObstacle(state, shot.row, shot.col)) { current.shots.push({ ...shot, result: 'miss' }); results.push({ ...shot, result: 'miss' }); continue; } const result = applyShot(target, shot); if (result !== 'repeat') { current.shots.push({ ...shot, result }); results.push({ ...shot, result }); } }
  const reveals = []; for (const cell of plan.reveal) { if (cell.row < 0 || cell.col < 0 || cell.row >= state.size || cell.col >= state.size) continue; const revealKey = key(cell.row, cell.col); if (current.shots.some(shot => key(shot.row, shot.col) === revealKey) || current.reveals.some(shot => key(shot.row, shot.col) === revealKey)) continue; const reveal = { ...cell, result: 'reveal', content: revealContent(state, target, cell.row, cell.col) }; current.reveals.push(reveal); reveals.push(reveal); }
  if (state.mode === 'plus' && (state.abilitiesEnabled || state.specialShotsEnabled)) updateCooldowns(current, valid.selected); if (allSunk(target)) { state.winner = action.playerId; state.phase = 'FINISHED'; } else state.turn = target.id; state.lastAction = { playerId: action.playerId, targetId: target.id, results, reveals }; return { ok: true, state, events: [{ type: 'attack_resolved', playerId: action.playerId, targetId: target.id, results, reveals }] }; }
function ownBoard(state, current) { const board = Array.from({ length: state.size }, () => Array(state.size).fill(null)); for (const obstacle of state.obstacles) board[obstacle.row][obstacle.col] = { type: 'obstacle', obstacle: obstacle.type }; for (const ship of current.ships) { const sunk = shipIsSunk(current, ship); for (const cell of cellsFor(ship)) board[cell.row][cell.col] = { type: ship.typeId, hit: ship.hits.includes(key(cell.row, cell.col)), sunk }; } for (const shot of current.receivedShots) if (board[shot.row][shot.col] && board[shot.row][shot.col].type !== 'obstacle') board[shot.row][shot.col].hit = true; return board; }
function opponentBoard(state, current, target) { const board = Array.from({ length: state.size }, () => Array(state.size).fill(null)); for (const reveal of current.reveals || []) board[reveal.row][reveal.col] = reveal.content; for (const shot of current.shots) { const hitShip = target.ships.find(ship => cellsFor(ship).some(cell => cell.row === shot.row && cell.col === shot.col)); const sunk = hitShip && shipIsSunk(target, hitShip); board[shot.row][shot.col] = hitShip ? sunk ? { type: 'sunk', shipType: hitShip.typeId } : { type: 'hit' } : { type: 'miss' }; } return board; }
function getView(state, viewerId) { const current = player(state, viewerId); const target = enemy(state, viewerId); const boardsVisible = ['SETUP', 'PLAY', 'FINISHED'].includes(state.phase); const activity = state.lastAction && (state.lastAction.playerId === viewerId || state.lastAction.targetId === viewerId) ? { playerId: state.lastAction.playerId, targetId: state.lastAction.targetId, results: state.lastAction.results, reveals: state.lastAction.playerId === viewerId ? state.lastAction.reveals : [] } : null; const sunkShips = ['PLAY', 'FINISHED'].includes(state.phase) ? target.ships.filter(ship => shipIsSunk(target, ship)).map(ship => ({ ...ship, sunk: true })) : []; return { mode: state.mode, fleetSet: state.fleetSet, size: state.size, deckBudget: state.deckBudget, minDeckShips: state.minDeckShips, abilitiesEnabled: state.abilitiesEnabled, specialShotsEnabled: state.specialShotsEnabled, phase: state.phase, turn: state.turn, winner: state.winner, lastAction: activity, obstacles: boardsVisible ? state.obstacles : [], ownBoard: boardsVisible ? ownBoard(state, current) : null, opponentBoard: ['PLAY', 'FINISHED'].includes(state.phase) ? opponentBoard(state, current, target) : null, fleet: current.fleet, deck: current.deck, deckReady: current.deckReady, ships: current.ships, sunkShips, shipTypes: SHIP_TYPES, fleetSets: CLASSIC_FLEET_SETS, players: state.players.map(item => ({ id: item.id, ready: item.ready, deckReady: item.deckReady, shipCount: item.ships.length, deckCount: item.deck.length })) }; }
function result(state) { return state.winner ? { status: 'WON', winnerId: state.winner } : null; }
module.exports = { SHIP_TYPES, PLUS_SHIP_TYPES, CLASSIC_FLEET, CLASSIC_FLEET_SETS, CLASSIC_BOARD_SIZES, PLUS_BOARD_OPTIONS, PLUS_MIN_SHIPS, clampSize, deckBudget, createInitialState, validateAction, reduce, result, getView };
