const COLORS = ['red', 'yellow', 'green', 'blue'];
const MODES = { classic: 'Classica', stack: 'Stack selvaggio', chaos: 'Caos' };
function shuffle(items) { const result = items.slice(); for (let i = result.length - 1; i > 0; i -= 1) { const j = Math.floor(Math.random() * (i + 1)); [result[i], result[j]] = [result[j], result[i]]; } return result; }
function buildDeck() { const cards = []; let id = 0; for (const color of COLORS) { cards.push({ id: `card_${id += 1}`, color, value: '0' }); for (let n = 1; n <= 9; n += 1) { cards.push({ id: `card_${id += 1}`, color, value: String(n) }, { id: `card_${id += 1}`, color, value: String(n) }); } for (const value of ['skip', 'reverse', 'draw2']) for (let copy = 0; copy < 2; copy += 1) cards.push({ id: `card_${id += 1}`, color, value }); } for (const value of ['wild', 'wild4']) for (let copy = 0; copy < 4; copy += 1) cards.push({ id: `card_${id += 1}`, color: 'wild', value }); return shuffle(cards); }
function drawCards(state, amount) { const cards = []; for (let i = 0; i < amount; i += 1) { if (!state.drawPile.length) { const top = state.discardPile.pop(); state.drawPile = shuffle(state.discardPile); state.discardPile = top ? [top] : []; } if (state.drawPile.length) cards.push(state.drawPile.pop()); } return cards; }
function createInitialState(players = [], settings = {}) { const mode = MODES[settings.mode] ? settings.mode : 'classic'; const drawPile = buildDeck(); const state = { mode, modeName: MODES[mode], drawPile, discardPile: [], currentColor: null, players: players.map(player => ({ id: player.id, hand: [], calledUno: false })), turn: players[0]?.id || null, direction: 1, pendingDraw: 0, winner: null, lastAction: null }; for (const player of state.players) player.hand = drawCards(state, 7); let first = drawCards(state, 1)[0]; while (first && ['wild', 'wild4'].includes(first.value)) { state.drawPile.unshift(first); first = drawCards(state, 1)[0]; } if (first) { state.discardPile.push(first); state.currentColor = first.color; } return state; }
function currentPlayer(state, id) { return state.players.find(player => player.id === id); }
function nextPlayer(state, fromId, steps = 1) { let index = state.players.findIndex(player => player.id === fromId); for (let i = 0; i < steps; i += 1) index = (index + state.direction + state.players.length) % state.players.length; return state.players[index]; }
function topCard(state) { return state.discardPile[state.discardPile.length - 1]; }
function playable(state, card) { const top = topCard(state); if (!top) return true; if (card.value === 'wild' || card.value === 'wild4') return state.mode === 'chaos' || card.value === 'wild' || !state.discardPile.some(item => item.color === state.currentColor); if (state.pendingDraw && state.mode === 'stack' && ['draw2', 'wild4'].includes(card.value)) return card.value === top.value || card.value === 'wild4'; if (state.pendingDraw) return false; return card.color === state.currentColor || card.value === top.value; }
function validateAction(state, action) { if (state.winner) return { ok: false, error: 'La partita è terminata.' }; if (action.playerId !== state.turn) return { ok: false, error: 'Non è il tuo turno.' }; const player = currentPlayer(state, action.playerId); if (!player) return { ok: false, error: 'Giocatore non autorizzato.' }; if (action.type === 'call_uno') return player.hand.length <= 2 ? { ok: true } : { ok: false, error: 'Puoi chiamare UNO solo quando hai una o due carte.' }; if (action.type === 'draw_card') return { ok: true }; if (action.type !== 'play_card') return { ok: false, error: 'Azione sconosciuta.' }; const card = player.hand.find(item => item.id === action.payload?.cardId); if (!card) return { ok: false, error: 'Carta non trovata.' }; if (!playable(state, card)) return { ok: false, error: 'Questa carta non è giocabile.' }; if (card.value === 'wild4' && state.mode !== 'chaos' && player.hand.some(item => item.color !== 'wild' && item.color === state.currentColor)) return { ok: false, error: 'Il Wild +4 può essere usato solo senza altre carte del colore corrente.' }; if (['wild', 'wild4'].includes(card.value) && !COLORS.includes(action.payload?.color)) return { ok: false, error: 'Scegli il colore del prossimo turno.' }; return { ok: true, player, card }; }
function reduce(state, action) { const valid = validateAction(state, action); if (!valid.ok) return { ok: false, error: valid.error, state }; const player = currentPlayer(state, action.playerId); if (action.type === 'call_uno') { player.calledUno = true; return { ok: true, state, events: [{ type: 'uno_called', playerId: action.playerId }] }; } if (action.type === 'draw_card') { const amount = state.pendingDraw || 1; player.hand.push(...drawCards(state, amount)); state.pendingDraw = 0; player.calledUno = false; state.turn = nextPlayer(state, action.playerId).id; state.lastAction = { type: 'draw_card', playerId: action.playerId, amount }; return { ok: true, state, events: [{ type: 'card_drawn', playerId: action.playerId, amount }] }; } const cardIndex = player.hand.findIndex(item => item.id === valid.card.id); player.hand.splice(cardIndex, 1); state.discardPile.push(valid.card); state.currentColor = valid.card.value.startsWith('wild') ? action.payload.color : valid.card.color; state.pendingDraw = valid.card.value === 'draw2' ? state.pendingDraw + 2 : valid.card.value === 'wild4' ? state.pendingDraw + 4 : 0; let steps = 1; if (valid.card.value === 'skip') steps = 2; if (valid.card.value === 'reverse') { state.direction *= -1; if (state.players.length === 2) steps = 2; } if (player.hand.length === 0) state.winner = player.id; else if (player.hand.length === 1 && !player.calledUno) { player.hand.push(...drawCards(state, 2)); } player.calledUno = false; if (!state.winner) state.turn = nextPlayer(state, action.playerId, steps).id; state.lastAction = { type: 'play_card', playerId: action.playerId, card: valid.card, color: state.currentColor }; return { ok: true, state, events: [{ type: 'card_played', playerId: action.playerId, card: valid.card }] }; }
function getView(state, viewerId) { return { mode: state.mode, modeName: state.modeName, currentColor: state.currentColor, topCard: topCard(state), turn: state.turn, direction: state.direction, pendingDraw: state.pendingDraw, winner: state.winner, hand: currentPlayer(state, viewerId)?.hand || [], players: state.players.map(player => ({ id: player.id, cardCount: player.hand.length, calledUno: player.calledUno })), lastAction: state.lastAction }; }
function result(state) { return state.winner ? { status: 'WON', winnerId: state.winner } : null; }
module.exports = { COLORS, MODES, createInitialState, validateAction, reduce, getView, result };
