const WORDS = ['MAREO', 'FIORI', 'NOTTE', 'CUORE', 'MAREA', 'SOGNO', 'VENTO', 'TERRA', 'LUNGA', 'PISTA', 'PONTE', 'NEVEA'];
const MIN_GUESSES = 5;
const MAX_GUESSES = 10;
function shuffle(items) { const result = items.slice(); for (let i = result.length - 1; i > 0; i -= 1) { const j = Math.floor(Math.random() * (i + 1)); [result[i], result[j]] = [result[j], result[i]]; } return result; }
function evaluate(guess, target) { const result = Array(5).fill('absent'); const counts = {}; for (const letter of target) counts[letter] = (counts[letter] || 0) + 1; for (let index = 0; index < 5; index += 1) if (guess[index] === target[index]) { result[index] = 'correct'; counts[guess[index]] -= 1; } for (let index = 0; index < 5; index += 1) if (result[index] !== 'correct' && counts[guess[index]] > 0) { result[index] = 'present'; counts[guess[index]] -= 1; } return result; }
function makeBoard(target) { return { target, guesses: [], solved: false, failed: false, maxGuesses: MIN_GUESSES }; }
function createInitialState(players = [], settings = {}) { const wordCount = Math.max(1, Math.min(5, Number(settings.wordCount) || 1)); const targets = shuffle(WORDS).slice(0, wordCount); const variant = settings.variant === 'competitive' ? 'competitive' : 'coop'; const matchMode = settings.matchMode === 'time' ? 'time' : 'first'; const durationSeconds = Math.max(30, Math.min(600, Number(settings.durationSeconds) || 120)); const adaptiveGuesses = settings.guessMode === 'adaptive'; const fixedGuesses = Math.max(MIN_GUESSES, Math.min(MAX_GUESSES, Number(settings.guesses) || 6)); return { variant, matchMode, wordCount, maxGuesses: adaptiveGuesses ? MIN_GUESSES : fixedGuesses, adaptiveGuesses, fixedGuesses, durationSeconds, startedAt: Date.now(), targets, boards: variant === 'coop' ? targets.map(makeBoard) : null, players: players.map(player => ({ id: player.id, boards: variant === 'competitive' ? targets.map(makeBoard) : null, score: 0, lost: false, finishedAt: null })), winner: null, draw: false, lost: false, lastGuess: null }; }
function activeBoards(state, playerId) { return state.variant === 'coop' ? state.boards : state.players.find(player => player.id === playerId)?.boards; }
function scorePlayer(player) { return player.boards.filter(board => board.solved).length; }
function timeExpired(state) { return state.matchMode === 'time' && Date.now() >= state.startedAt + state.durationSeconds * 1000; }
function settleTime(state) { if (!timeExpired(state) || state.winner) return; const best = Math.max(...state.players.map(player => scorePlayer(player))); const leaders = state.players.filter(player => scorePlayer(player) === best); if (leaders.length === 1) state.winner = leaders[0].id; else state.draw = true; }
function validateAction(state, action) { if (state.winner || state.draw || state.lost) return { ok: false, error: 'La partita è terminata.' }; if (action.type !== 'submit_guess') return { ok: false, error: 'Azione sconosciuta.' }; const player = state.players.find(item => item.id === action.playerId); if (!player) return { ok: false, error: 'Giocatore non autorizzato.' }; settleTime(state); if (state.winner || state.draw) return { ok: false, error: 'Il tempo è scaduto.' }; const boards = activeBoards(state, action.playerId) || []; if (!boards.some(board => !board.solved && !board.failed)) return { ok: false, error: 'Hai esaurito i tentativi.' }; const guess = String(action.payload?.guess || '').trim().toUpperCase(); if (!/^[A-ZÀ-Ü]{5}$/.test(guess)) return { ok: false, error: 'La parola deve avere 5 lettere.' }; return { ok: true, guess }; }
function applyGuess(board, guess, adaptiveGuesses) { if (board.solved || board.failed) return null; const evaluation = evaluate(guess, board.target); board.guesses.push({ guess, evaluation }); if (guess === board.target) { board.solved = true; if (adaptiveGuesses) board.maxGuesses = Math.min(MAX_GUESSES, board.maxGuesses + 1); } else if (board.guesses.length >= board.maxGuesses) board.failed = true; return board.guesses.at(-1); }
function allBoardsClosed(boards) { return boards.every(board => board.solved || board.failed); }
function reduce(state, action) { const valid = validateAction(state, action); if (!valid.ok) return { ok: false, error: valid.error, state }; const affected = []; if (state.variant === 'coop') { state.boards.forEach((board, index) => { const entry = applyGuess(board, valid.guess, state.adaptiveGuesses); if (entry) affected.push({ index, entry }); }); if (state.adaptiveGuesses) state.maxGuesses = Math.min(MAX_GUESSES, MIN_GUESSES + state.boards.filter(board => board.solved).length); else state.maxGuesses = state.fixedGuesses; if (state.boards.some(board => board.failed)) state.lost = true; else if (state.boards.every(board => board.solved)) state.winner = action.playerId; } else { const player = state.players.find(item => item.id === action.playerId); player.boards.forEach((board, index) => { const entry = applyGuess(board, valid.guess, state.adaptiveGuesses); if (entry) affected.push({ index, entry }); }); player.score = scorePlayer(player); if (state.matchMode === 'first' && player.score === state.wordCount) { player.finishedAt = Date.now(); state.winner = player.id; } else if (allBoardsClosed(player.boards)) { player.lost = player.score < state.wordCount; player.finishedAt = Date.now(); if (state.players.every(item => item.lost || scorePlayer(item) === state.wordCount)) state.draw = true; } } state.lastGuess = { playerId: action.playerId, guess: valid.guess, affected }; if (state.matchMode === 'time') settleTime(state); return { ok: true, state, events: [{ type: 'word_guessed', playerId: action.playerId, guess: valid.guess, affected }] }; }
function viewBoard(board, reveal = false) { return { solved: board.solved, failed: board.failed, guesses: board.guesses, maxGuesses: board.maxGuesses, ...(reveal ? { target: board.target } : {}) }; }
function getView(state, viewerId) { const ownBoards = activeBoards(state, viewerId) || []; const secondsLeft = state.matchMode === 'time' ? Math.max(0, Math.ceil((state.startedAt + state.durationSeconds * 1000 - Date.now()) / 1000)) : null; const viewer = state.players.find(player => player.id === viewerId); const reveal = Boolean(state.winner || state.draw || state.lost || viewer?.lost); return { variant: state.variant, matchMode: state.matchMode, wordCount: state.wordCount, maxGuesses: state.adaptiveGuesses ? MIN_GUESSES + ownBoards.filter(board => board.solved).length : state.fixedGuesses, adaptiveGuesses: state.adaptiveGuesses, durationSeconds: state.durationSeconds, secondsLeft, startedAt: state.startedAt, boards: ownBoards.map(board => viewBoard(board, reveal || board.failed)), players: state.players.map(player => ({ id: player.id, score: state.variant === 'competitive' ? scorePlayer(player) : state.boards.filter(board => board.solved).length, lost: player.lost, finished: state.variant === 'competitive' ? player.lost || player.score === state.wordCount : state.lost || state.boards.every(board => board.solved) })), winner: state.winner, draw: state.draw, lost: state.lost, lastGuess: state.lastGuess }; }
function result(state) { return state.winner ? { status: 'WON', winnerId: state.winner } : state.draw ? { status: 'DRAW', winnerId: null } : state.lost ? { status: 'LOST', winnerId: null } : null; }
module.exports = { WORDS, MIN_GUESSES, MAX_GUESSES, evaluate, createInitialState, validateAction, reduce, getView, result };
